-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.accounting_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  period_name character varying NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  fiscal_year integer NOT NULL,
  period_type character varying CHECK (period_type::text = ANY (ARRAY['MONTHLY'::character varying, 'QUARTERLY'::character varying, 'YEARLY'::character varying]::text[])),
  status USER-DEFINED DEFAULT 'OPEN'::period_status,
  closed_by uuid,
  closed_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT accounting_periods_pkey PRIMARY KEY (id),
  CONSTRAINT accounting_periods_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES public.users(id)
);
CREATE TABLE public.alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type text NOT NULL,
  message text NOT NULL,
  priority text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT alerts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.analytics_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  snapshot_date date NOT NULL,
  metric_type character varying NOT NULL,
  dimensions jsonb DEFAULT '{}'::jsonb,
  metrics jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT analytics_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.attendance_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  date date NOT NULL,
  check_in_time timestamp without time zone,
  check_out_time timestamp without time zone,
  total_hours numeric,
  status text DEFAULT 'present'::text CHECK (status = ANY (ARRAY['present'::text, 'absent'::text, 'half_day'::text, 'late'::text, 'on_leave'::text])),
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT attendance_records_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_records_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.audit_trail (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name character varying NOT NULL,
  record_id uuid NOT NULL,
  action USER-DEFINED NOT NULL,
  old_values jsonb,
  new_values jsonb,
  changed_fields ARRAY,
  user_id uuid,
  ip_address inet,
  user_agent text,
  timestamp timestamp without time zone DEFAULT now(),
  description text,
  CONSTRAINT audit_trail_pkey PRIMARY KEY (id),
  CONSTRAINT audit_trail_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.bank_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  account_number text,
  current_balance numeric DEFAULT 0,
  currency text DEFAULT 'USD'::text,
  CONSTRAINT bank_accounts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bank_reconciliations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bank_account_id uuid NOT NULL,
  statement_date date NOT NULL,
  statement_ending_balance numeric NOT NULL,
  book_ending_balance numeric NOT NULL,
  reconciled_balance numeric,
  status USER-DEFINED DEFAULT 'PENDING'::reconciliation_status,
  reconciled_by uuid,
  reconciled_at timestamp without time zone,
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT bank_reconciliations_pkey PRIMARY KEY (id),
  CONSTRAINT bank_reconciliations_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
  CONSTRAINT bank_reconciliations_reconciled_by_fkey FOREIGN KEY (reconciled_by) REFERENCES public.users(id)
);
CREATE TABLE public.bank_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bank_account_id uuid,
  date date NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['deposit'::text, 'withdrawal'::text])),
  amount numeric NOT NULL,
  description text,
  reference text,
  CONSTRAINT bank_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT bank_transactions_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id)
);
CREATE TABLE public.boms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  component text,
  quantity integer,
  CONSTRAINT boms_pkey PRIMARY KEY (id),
  CONSTRAINT boms_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.cashflow_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date,
  amount numeric,
  direction text CHECK (direction = ANY (ARRAY['inflow'::text, 'outflow'::text])),
  description text,
  reference_type text,
  reference_id uuid,
  CONSTRAINT cashflow_entries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cashflow_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  month date NOT NULL,
  inflows numeric NOT NULL,
  outflows numeric NOT NULL,
  net_position numeric NOT NULL,
  CONSTRAINT cashflow_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chart_of_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_code character varying NOT NULL UNIQUE,
  account_name character varying NOT NULL,
  account_type USER-DEFINED NOT NULL,
  account_subtype USER-DEFINED NOT NULL,
  parent_account_id uuid,
  description text,
  is_active boolean DEFAULT true,
  normal_balance text NOT NULL CHECK (normal_balance = ANY (ARRAY['DEBIT'::text, 'CREDIT'::text])),
  current_balance numeric DEFAULT 0,
  opening_balance numeric DEFAULT 0,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT chart_of_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT chart_of_accounts_parent_account_id_fkey FOREIGN KEY (parent_account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT chart_of_accounts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.custom_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  config_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  sku text,
  description text,
  price numeric DEFAULT 0,
  supplier_name text,
  supplier_id uuid,
  CONSTRAINT custom_products_pkey PRIMARY KEY (id),
  CONSTRAINT custom_products_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.customer_interactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid,
  type text,
  notes text,
  interaction_date timestamp without time zone,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT customer_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT customer_interactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT customer_interactions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text UNIQUE,
  phone text,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  status text NOT NULL DEFAULT 'Lead'::text,
  source text NOT NULL DEFAULT 'Website'::text,
  tags ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  updated_at timestamp without time zone DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  updated_by uuid,
  address text,
  city character varying,
  state character varying,
  pincode character varying,
  notes text,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_customers_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_customers_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.daysheets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date NOT NULL UNIQUE,
  total_sales numeric DEFAULT 0,
  total_receipts numeric DEFAULT 0,
  total_expenses numeric DEFAULT 0,
  total_purchases numeric DEFAULT 0,
  cash_position numeric DEFAULT 0,
  bank_balance numeric DEFAULT 0,
  net_position numeric DEFAULT 0,
  is_closed boolean DEFAULT false,
  closed_by uuid,
  closed_at timestamp without time zone,
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT daysheets_pkey PRIMARY KEY (id),
  CONSTRAINT daysheets_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES public.users(id)
);
CREATE TABLE public.deliveries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sales_order_id uuid,
  driver_id uuid,
  status USER-DEFINED DEFAULT 'pending'::delivery_status,
  tracking_number text,
  updated_at timestamp without time zone DEFAULT now(),
  time_slot text,
  created_at timestamp without time zone DEFAULT now(),
  delivery_notes text,
  CONSTRAINT deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT deliveries_sales_order_id_fkey FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id),
  CONSTRAINT deliveries_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.users(id)
);
CREATE TABLE public.delivery_proofs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  delivery_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['photo'::text, 'signature'::text])),
  url text NOT NULL,
  timestamp timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT delivery_proofs_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_proofs_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES public.deliveries(id)
);
CREATE TABLE public.employee_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  document_type text NOT NULL,
  document_name text NOT NULL,
  file_url text NOT NULL,
  expiry_date date,
  is_verified boolean DEFAULT false,
  verified_by uuid,
  verified_at timestamp without time zone,
  uploaded_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT employee_documents_pkey PRIMARY KEY (id),
  CONSTRAINT employee_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id),
  CONSTRAINT employee_documents_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.employee_leave_balances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  leave_type_id uuid NOT NULL,
  year integer NOT NULL,
  allocated_days numeric DEFAULT 0,
  used_days numeric DEFAULT 0,
  remaining_days numeric DEFAULT 0,
  carry_forward_days numeric DEFAULT 0,
  CONSTRAINT employee_leave_balances_pkey PRIMARY KEY (id),
  CONSTRAINT employee_leave_balances_leave_type_id_fkey FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id),
  CONSTRAINT employee_leave_balances_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_trainings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  training_program_id uuid NOT NULL,
  enrollment_date date,
  start_date date,
  completion_date date,
  status text DEFAULT 'enrolled'::text CHECK (status = ANY (ARRAY['enrolled'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  score numeric,
  feedback text,
  certificate_url text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT employee_trainings_pkey PRIMARY KEY (id),
  CONSTRAINT employee_trainings_training_program_id_fkey FOREIGN KEY (training_program_id) REFERENCES public.training_programs(id),
  CONSTRAINT employee_trainings_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text,
  email text,
  position text,
  salary numeric,
  created_at timestamp without time zone DEFAULT now(),
  user_id uuid,
  employee_id text UNIQUE,
  department text,
  hire_date date,
  employment_type text CHECK (employment_type = ANY (ARRAY['full_time'::text, 'part_time'::text, 'contract'::text, 'intern'::text])),
  employment_status text DEFAULT 'active'::text CHECK (employment_status = ANY (ARRAY['active'::text, 'inactive'::text, 'terminated'::text, 'on_leave'::text])),
  phone text,
  address text,
  emergency_contact_name text,
  emergency_contact_phone text,
  date_of_birth date,
  gender text,
  nationality text,
  marital_status text,
  manager_id uuid,
  updated_at timestamp without time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT employees_pkey PRIMARY KEY (id),
  CONSTRAINT employees_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.employees(id),
  CONSTRAINT employees_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT employees_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['Rent'::text, 'Utilities'::text, 'Salaries'::text, 'Marketing'::text, 'Other'::text, 'Manufacturing'::text, 'Production'::text, 'Maintenance'::text, 'Administration'::text, 'Insurance'::text, 'Logistics'::text])),
  description text,
  amount numeric NOT NULL,
  payment_method text,
  created_by uuid,
  type text CHECK (type = ANY (ARRAY['Direct'::text, 'Indirect'::text, 'Fixed'::text, 'Variable'::text])),
  CONSTRAINT expenses_pkey PRIMARY KEY (id),
  CONSTRAINT expenses_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.general_ledger (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid NOT NULL,
  journal_entry_id uuid NOT NULL,
  journal_line_id uuid NOT NULL,
  transaction_date date NOT NULL,
  posting_date date NOT NULL,
  description text NOT NULL,
  reference character varying,
  debit_amount numeric DEFAULT 0,
  credit_amount numeric DEFAULT 0,
  running_balance numeric NOT NULL,
  source_document_type character varying,
  source_document_id uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT general_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT general_ledger_journal_line_id_fkey FOREIGN KEY (journal_line_id) REFERENCES public.journal_entry_lines(id),
  CONSTRAINT general_ledger_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT general_ledger_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id)
);
CREATE TABLE public.hr_policies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  policy_name text NOT NULL,
  policy_document_url text,
  version text,
  effective_date date,
  expiry_date date,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT hr_policies_pkey PRIMARY KEY (id),
  CONSTRAINT hr_policies_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.inventory_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  category text,
  subcategory text,
  material text,
  location text,
  quantity integer NOT NULL DEFAULT 0,
  reorder_point integer NOT NULL DEFAULT 0,
  supplier_id uuid,
  updated_at timestamp without time zone DEFAULT now(),
  qr_code_url text,
  CONSTRAINT inventory_items_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT inventory_items_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sales_order_id uuid,
  total numeric,
  status USER-DEFINED DEFAULT 'unpaid'::invoice_status,
  created_at timestamp without time zone DEFAULT now(),
  customer_id uuid,
  paid_amount numeric DEFAULT 0,
  customer_name text,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.journal_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  journal_number character varying NOT NULL UNIQUE,
  entry_date date NOT NULL,
  posting_date date,
  reference_number character varying,
  description text NOT NULL,
  entry_type USER-DEFINED DEFAULT 'STANDARD'::journal_entry_type,
  status USER-DEFINED DEFAULT 'DRAFT'::journal_status,
  total_debit numeric NOT NULL DEFAULT 0,
  total_credit numeric NOT NULL DEFAULT 0,
  source_document_type character varying,
  source_document_id uuid,
  created_by uuid NOT NULL,
  posted_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  posted_at timestamp without time zone,
  notes text,
  updated_by uuid,
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT journal_entries_pkey PRIMARY KEY (id),
  CONSTRAINT journal_entries_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES public.users(id),
  CONSTRAINT journal_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.journal_entry_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  journal_entry_id uuid NOT NULL,
  line_number integer NOT NULL,
  account_id uuid NOT NULL,
  description text,
  debit_amount numeric DEFAULT 0,
  credit_amount numeric DEFAULT 0,
  reference character varying,
  updated_at timestamp without time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT journal_entry_lines_pkey PRIMARY KEY (id),
  CONSTRAINT journal_entry_lines_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
  CONSTRAINT journal_entry_lines_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.journal_entry_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_name character varying NOT NULL,
  template_code character varying NOT NULL UNIQUE,
  description text,
  source_document_type character varying NOT NULL,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT journal_entry_templates_pkey PRIMARY KEY (id),
  CONSTRAINT journal_entry_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.journal_template_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid,
  line_number integer NOT NULL,
  account_code character varying NOT NULL,
  debit_formula text,
  credit_formula text,
  description_template text,
  is_conditional boolean DEFAULT false,
  condition_field character varying,
  condition_operator character varying,
  condition_value text,
  CONSTRAINT journal_template_lines_pkey PRIMARY KEY (id),
  CONSTRAINT journal_template_lines_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.journal_entry_templates(id)
);
CREATE TABLE public.leave_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  leave_type_id uuid NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  total_days numeric NOT NULL,
  reason text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text])),
  applied_date timestamp without time zone DEFAULT now(),
  approved_by uuid,
  approved_date timestamp without time zone,
  rejection_reason text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT leave_requests_pkey PRIMARY KEY (id),
  CONSTRAINT leave_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT leave_requests_leave_type_id_fkey FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id),
  CONSTRAINT leave_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.leave_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  max_days_per_year integer,
  carry_forward_allowed boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT leave_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.opening_balances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid,
  entity_type text CHECK (entity_type = ANY (ARRAY['customer'::text, 'supplier'::text, 'inventory'::text, 'bank'::text])),
  entity_id uuid,
  opening_date date NOT NULL,
  debit_amount numeric DEFAULT 0,
  credit_amount numeric DEFAULT 0,
  fiscal_year integer,
  period_id uuid,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT opening_balances_pkey PRIMARY KEY (id),
  CONSTRAINT opening_balances_period_id_fkey FOREIGN KEY (period_id) REFERENCES public.accounting_periods(id),
  CONSTRAINT opening_balances_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT opening_balances_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid,
  amount numeric,
  payment_date timestamp without time zone,
  date date DEFAULT now(),
  method text,
  reference text,
  description text,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.payroll_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  salary_structure_id uuid,
  pay_period_start date NOT NULL,
  pay_period_end date NOT NULL,
  basic_salary numeric,
  total_allowances numeric,
  total_deductions numeric,
  gross_salary numeric,
  net_salary numeric,
  working_days integer,
  present_days integer,
  leave_days integer,
  overtime_hours numeric DEFAULT 0,
  overtime_amount numeric DEFAULT 0,
  bonus numeric DEFAULT 0,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'processed'::text, 'paid'::text])),
  processed_by uuid,
  processed_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT payroll_records_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_records_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.users(id),
  CONSTRAINT payroll_records_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT payroll_records_salary_structure_id_fkey FOREIGN KEY (salary_structure_id) REFERENCES public.salary_structures(id)
);
CREATE TABLE public.performance_goals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  goal_title text NOT NULL,
  description text,
  target_date date,
  weightage numeric DEFAULT 0,
  status text DEFAULT 'not_started'::text CHECK (status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'completed'::text, 'overdue'::text])),
  achievement_percentage numeric DEFAULT 0,
  manager_rating integer CHECK (manager_rating >= 1 AND manager_rating <= 5),
  self_rating integer CHECK (self_rating >= 1 AND self_rating <= 5),
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT performance_goals_pkey PRIMARY KEY (id),
  CONSTRAINT performance_goals_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT performance_goals_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.performance_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid,
  reviewer_id uuid,
  score integer,
  feedback text,
  review_date timestamp without time zone,
  review_period_start date,
  review_period_end date,
  review_type text CHECK (review_type = ANY (ARRAY['annual'::text, 'mid_year'::text, 'probation'::text, 'project_based'::text])),
  goals_achievement jsonb DEFAULT '{}'::jsonb,
  strengths text,
  areas_for_improvement text,
  development_plan text,
  manager_comments text,
  employee_comments text,
  hr_comments text,
  overall_rating text CHECK (overall_rating = ANY (ARRAY['excellent'::text, 'good'::text, 'satisfactory'::text, 'needs_improvement'::text, 'unsatisfactory'::text])),
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'reviewed'::text, 'approved'::text])),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT performance_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT performance_reviews_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT performance_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id)
);
CREATE TABLE public.permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.policy_acknowledgments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  policy_id uuid NOT NULL,
  acknowledged_at timestamp without time zone DEFAULT now(),
  digital_signature text,
  CONSTRAINT policy_acknowledgments_pkey PRIMARY KEY (id),
  CONSTRAINT policy_acknowledgments_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.hr_policies(id),
  CONSTRAINT policy_acknowledgments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.production_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  work_order_id uuid,
  log_date date NOT NULL,
  output_quantity integer NOT NULL DEFAULT 0,
  defects integer NOT NULL DEFAULT 0,
  downtime_hours numeric DEFAULT 0,
  efficiency_percentage numeric DEFAULT 0,
  quality_score numeric DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT production_logs_pkey PRIMARY KEY (id),
  CONSTRAINT production_logs_work_order_id_fkey FOREIGN KEY (work_order_id) REFERENCES public.work_orders(id),
  CONSTRAINT production_logs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  sku text UNIQUE,
  description text,
  category text,
  price numeric,
  created_at timestamp without time zone DEFAULT now(),
  image_url text,
  supplier_id uuid,
  updated_at timestamp without time zone DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  created_by uuid,
  updated_by uuid,
  config_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
  cost numeric,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT fk_products_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_products_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.profit_margins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  margin_percentage numeric NOT NULL,
  product_id uuid,
  category text,
  subcategory text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profit_margins_pkey PRIMARY KEY (id),
  CONSTRAINT profit_margins_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.purchase_order_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_order_id uuid NOT NULL,
  url text NOT NULL,
  uploaded_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT purchase_order_images_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_images_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id)
);
CREATE TABLE public.purchase_order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  purchase_order_id uuid NOT NULL,
  sales_order_item_id uuid,
  quote_custom_item_id uuid,
  item_name text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0,
  total_price numeric DEFAULT ((quantity)::numeric * unit_price),
  specifications text,
  materials jsonb,
  dimensions text,
  finish text,
  color text,
  custom_instructions text,
  base_product_name text,
  image_url text,
  supplier_id uuid,
  supplier_name text,
  item_type text NOT NULL DEFAULT 'regular'::text CHECK (item_type = ANY (ARRAY['regular'::text, 'custom'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT purchase_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_items_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT purchase_order_items_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT purchase_order_items_sales_order_item_id_fkey FOREIGN KEY (sales_order_item_id) REFERENCES public.sales_order_items(id),
  CONSTRAINT purchase_order_items_quote_custom_item_id_fkey FOREIGN KEY (quote_custom_item_id) REFERENCES public.quote_custom_items(id)
);
CREATE TABLE public.purchase_order_materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_order_id uuid NOT NULL,
  material text NOT NULL,
  CONSTRAINT purchase_order_materials_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_materials_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id)
);
CREATE TABLE public.purchase_order_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_order_id uuid,
  amount numeric,
  payment_date timestamp without time zone DEFAULT now(),
  payment_method text DEFAULT 'cash'::text,
  reference_number text,
  notes text,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  status text DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  bank_account_id uuid,
  CONSTRAINT purchase_order_payments_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_payments_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT purchase_order_payments_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
  CONSTRAINT purchase_order_payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.purchase_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid,
  product_id uuid,
  quantity integer,
  status USER-DEFINED DEFAULT 'pending'::purchase_order_status,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  is_custom boolean NOT NULL DEFAULT false,
  custom_type text,
  description text,
  total numeric,
  due_date date,
  payment_status USER-DEFINED DEFAULT 'unpaid'::payment_status,
  paid_amount numeric DEFAULT 0,
  product_name text,
  sales_order_id uuid,
  CONSTRAINT purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT purchase_orders_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT purchase_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.quote_custom_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  name text NOT NULL,
  quantity integer NOT NULL,
  unit_price numeric NOT NULL,
  configuration jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  product_id uuid,
  supplier_id uuid,
  supplier_name text,
  image_url text,
  discount_percentage numeric DEFAULT 0,
  item_type text DEFAULT 'custom'::text CHECK (item_type = ANY (ARRAY['custom'::text, 'new'::text, 'customized_existing'::text])),
  base_product_name text,
  specifications text,
  materials jsonb DEFAULT '[]'::jsonb,
  dimensions text,
  finish text,
  color text,
  custom_instructions text,
  estimated_delivery_days integer DEFAULT 30,
  complexity_level text DEFAULT 'medium'::text CHECK (complexity_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_production'::text, 'ready'::text, 'delivered'::text])),
  notes text,
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT quote_custom_items_pkey PRIMARY KEY (id),
  CONSTRAINT quote_custom_items_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT quote_custom_items_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.quotes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid,
  items jsonb,
  total_price numeric,
  status text DEFAULT 'Draft'::text,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  customer text,
  discount_amount numeric DEFAULT 0,
  emi_enabled boolean DEFAULT false,
  emi_plan jsonb,
  emi_monthly numeric DEFAULT 0,
  original_price numeric DEFAULT 0,
  final_price numeric DEFAULT 0,
  notes text,
  bajaj_finance_amount numeric,
  freight_charges numeric,
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT quotes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.reconciliation_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reconciliation_id uuid,
  transaction_id uuid,
  transaction_type character varying,
  description text NOT NULL,
  amount numeric NOT NULL,
  item_type character varying CHECK (item_type::text = ANY (ARRAY['OUTSTANDING_CHECK'::character varying, 'DEPOSIT_IN_TRANSIT'::character varying, 'BANK_FEE'::character varying, 'INTEREST'::character varying, 'ERROR'::character varying, 'OTHER'::character varying]::text[])),
  is_cleared boolean DEFAULT false,
  cleared_date date,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT reconciliation_items_pkey PRIMARY KEY (id),
  CONSTRAINT reconciliation_items_reconciliation_id_fkey FOREIGN KEY (reconciliation_id) REFERENCES public.bank_reconciliations(id)
);
CREATE TABLE public.risk_incidents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type text NOT NULL,
  description text,
  severity text CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  status text CHECK (status = ANY (ARRAY['open'::text, 'investigating'::text, 'resolved'::text, 'closed'::text])),
  reported_date date DEFAULT CURRENT_DATE,
  resolved_date date,
  impact_cost numeric DEFAULT 0,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT risk_incidents_pkey PRIMARY KEY (id),
  CONSTRAINT risk_incidents_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.role_permissions (
  role_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id),
  CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.salary_structures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  basic_salary numeric NOT NULL,
  house_rent_allowance numeric DEFAULT 0,
  transport_allowance numeric DEFAULT 0,
  medical_allowance numeric DEFAULT 0,
  other_allowances jsonb DEFAULT '{}'::jsonb,
  provident_fund_deduction numeric DEFAULT 0,
  tax_deduction numeric DEFAULT 0,
  other_deductions jsonb DEFAULT '{}'::jsonb,
  effective_from date NOT NULL,
  effective_to date,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT salary_structures_pkey PRIMARY KEY (id),
  CONSTRAINT salary_structures_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT salary_structures_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.sales_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  product_id uuid,
  quantity integer NOT NULL,
  unit_price numeric NOT NULL,
  discount_percentage numeric DEFAULT 0,
  custom_product_id uuid,
  name text,
  supplier_name text,
  supplier_id uuid,
  final_price numeric,
  cost numeric DEFAULT 0,
  CONSTRAINT sales_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT sales_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT sales_order_items_custom_product_id_fkey FOREIGN KEY (custom_product_id) REFERENCES public.custom_products(id),
  CONSTRAINT sales_order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.sales_orders(id)
);
CREATE TABLE public.sales_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid,
  customer_id uuid,
  status USER-DEFINED DEFAULT 'draft'::sales_order_status,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  updated_by uuid,
  po_created boolean DEFAULT false,
  address text,
  expected_delivery_date date,
  notes text,
  final_price numeric,
  original_price numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  emi_enabled boolean DEFAULT false,
  emi_plan jsonb DEFAULT '{}'::jsonb,
  emi_monthly numeric DEFAULT 0,
  bajaj_finance_amount numeric DEFAULT 0,
  freight_charges numeric DEFAULT 0,
  sales_representative_id uuid,
  CONSTRAINT sales_orders_pkey PRIMARY KEY (id),
  CONSTRAINT sales_orders_sales_representative_id_fkey FOREIGN KEY (sales_representative_id) REFERENCES public.users(id),
  CONSTRAINT sales_orders_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT sales_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT sales_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_sales_orders_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_sales_orders_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.settings (
  key text NOT NULL,
  value text NOT NULL,
  description text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT settings_pkey PRIMARY KEY (key)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text,
  contact text,
  updated_at timestamp without time zone DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  address text,
  email text,
  CONSTRAINT suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT fk_suppliers_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT fk_suppliers_created_by FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title character varying NOT NULL,
  description text NOT NULL,
  status character varying DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying]::text[])),
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  category character varying,
  assigned_to uuid,
  resolution_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT support_tickets_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  assigned_to uuid,
  status text CHECK (status = ANY (ARRAY['To Do'::text, 'In Progress'::text, 'Done'::text, 'Cancelled'::text])),
  priority text CHECK (priority = ANY (ARRAY['Low'::text, 'Medium'::text, 'High'::text, 'Critical'::text])),
  due_date date,
  completed_date date,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.employees(id)
);
CREATE TABLE public.tax_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tax_code character varying NOT NULL UNIQUE,
  tax_name character varying NOT NULL,
  tax_type USER-DEFINED NOT NULL,
  tax_rate numeric NOT NULL,
  description text,
  account_id uuid,
  is_active boolean DEFAULT true,
  effective_from date NOT NULL,
  effective_to date,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT tax_codes_pkey PRIMARY KEY (id),
  CONSTRAINT tax_codes_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.training_programs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  duration_hours integer,
  trainer_name text,
  training_type text CHECK (training_type = ANY (ARRAY['internal'::text, 'external'::text, 'online'::text])),
  max_participants integer,
  cost_per_participant numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT training_programs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_notification_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  push_notifications boolean DEFAULT true,
  email_notifications boolean DEFAULT true,
  order_alerts boolean DEFAULT true,
  system_alerts boolean DEFAULT true,
  marketing_emails boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_notification_settings_pkey PRIMARY KEY (id),
  CONSTRAINT user_notification_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text,
  role_id uuid NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  password text,
  name text,
  is_deleted boolean NOT NULL DEFAULT false,
  image_url text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES public.roles(id)
);
CREATE TABLE public.vendor_bills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL,
  bill_number text NOT NULL,
  bill_date date NOT NULL,
  due_date date NOT NULL,
  total_amount numeric NOT NULL,
  paid_amount numeric DEFAULT 0,
  remaining_amount numeric DEFAULT (total_amount - paid_amount),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'partial'::text, 'paid'::text, 'overdue'::text, 'cancelled'::text])),
  description text,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  purchase_order_id uuid,
  attachment_url text,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  reference_number text,
  updated_by uuid,
  CONSTRAINT vendor_bills_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_bills_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT vendor_bills_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT vendor_bills_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id)
);
CREATE TABLE public.vendor_payment_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL,
  vendor_bill_id uuid,
  purchase_order_id uuid,
  amount numeric NOT NULL,
  payment_date date NOT NULL,
  payment_method text DEFAULT 'cash'::text CHECK (payment_method = ANY (ARRAY['cash'::text, 'bank_transfer'::text, 'cheque'::text, 'upi'::text, 'card'::text, 'other'::text])),
  reference_number text,
  bank_account_id uuid,
  notes text,
  status text DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT vendor_payment_history_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_payment_history_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT vendor_payment_history_vendor_bill_id_fkey FOREIGN KEY (vendor_bill_id) REFERENCES public.vendor_bills(id),
  CONSTRAINT vendor_payment_history_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT vendor_payment_history_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT vendor_payment_history_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id)
);
CREATE TABLE public.vendor_payment_terms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL,
  payment_terms_days integer DEFAULT 30,
  early_payment_discount_percentage numeric DEFAULT 0,
  early_payment_days integer DEFAULT 0,
  late_payment_penalty_percentage numeric DEFAULT 0,
  credit_limit numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT vendor_payment_terms_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_payment_terms_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT vendor_payment_terms_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.work_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bom_id uuid,
  product_id uuid,
  quantity integer NOT NULL DEFAULT 1,
  status text NOT NULL CHECK (status = ANY (ARRAY['planned'::text, 'in_progress'::text, 'quality_check'::text, 'completed'::text, 'delayed'::text])),
  progress integer NOT NULL DEFAULT 0,
  stage text,
  order_id uuid,
  assigned_to uuid,
  due_date date,
  notes text,
  created_by uuid,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  start_date timestamp without time zone,
  product text,
  updated_at timestamp without time zone DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  updated_by uuid,
  CONSTRAINT work_orders_pkey PRIMARY KEY (id),
  CONSTRAINT work_orders_bom_id_fkey FOREIGN KEY (bom_id) REFERENCES public.boms(id),
  CONSTRAINT fk_work_orders_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT fk_work_orders_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT work_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT work_orders_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT work_orders_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.work_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  day_of_week integer CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone,
  end_time time without time zone,
  is_working_day boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT work_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT work_schedules_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);