-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.accounting_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  period_name character varying NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  fiscal_year integer NOT NULL,
  period_type character varying CHECK (period_type::text = ANY (ARRAY['MONTHLY'::character varying, 'QUARTERLY'::character varying, 'YEARLY'::character varying]::text[])),
  status USER-DEFINED DEFAULT 'OPEN'::period_status,
  closed_by uuid,
  closed_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT accounting_periods_pkey PRIMARY KEY (id),
  CONSTRAINT accounting_periods_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES public.users(id)
);
CREATE TABLE public.alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type text NOT NULL,
  message text NOT NULL,
  priority text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT alerts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.analytics_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  snapshot_date date NOT NULL,
  metric_type character varying NOT NULL,
  dimensions jsonb DEFAULT '{}'::jsonb,
  metrics jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT analytics_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.attendance_corrections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  original_record_id uuid,
  correction_date date NOT NULL,
  original_check_in timestamp without time zone,
  corrected_check_in timestamp without time zone,
  original_check_out timestamp without time zone,
  corrected_check_out timestamp without time zone,
  reason text NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  requested_by uuid NOT NULL,
  approved_by uuid,
  approved_at timestamp without time zone,
  comments text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT attendance_corrections_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_corrections_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT attendance_corrections_original_record_id_fkey FOREIGN KEY (original_record_id) REFERENCES public.attendance_records(id),
  CONSTRAINT attendance_corrections_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.users(id),
  CONSTRAINT attendance_corrections_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.attendance_policies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  policy_name character varying NOT NULL,
  late_arrival_policy jsonb,
  early_departure_policy jsonb,
  overtime_policy jsonb,
  break_policy jsonb,
  minimum_hours_policy jsonb,
  is_active boolean DEFAULT true,
  effective_from date NOT NULL,
  effective_to date,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT attendance_policies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.attendance_punch_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  device_id uuid NOT NULL,
  punch_time timestamp without time zone NOT NULL,
  punch_type character varying NOT NULL CHECK (punch_type::text = ANY (ARRAY['IN'::character varying, 'OUT'::character varying, 'BREAK'::character varying]::text[])),
  verification_method character varying NOT NULL,
  verification_quality integer,
  device_user_id character varying,
  raw_data jsonb,
  processed boolean DEFAULT false,
  attendance_record_id uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT attendance_punch_logs_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_punch_logs_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT attendance_punch_logs_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.essl_devices(id),
  CONSTRAINT attendance_punch_logs_attendance_record_id_fkey FOREIGN KEY (attendance_record_id) REFERENCES public.attendance_records(id)
);
CREATE TABLE public.attendance_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  date date NOT NULL,
  check_in_time timestamp without time zone,
  check_out_time timestamp without time zone,
  total_hours numeric,
  status text DEFAULT 'present'::text CHECK (status = ANY (ARRAY['present'::text, 'absent'::text, 'half_day'::text, 'late'::text, 'on_leave'::text])),
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  device_id uuid,
  punch_type character varying DEFAULT 'auto'::character varying CHECK (punch_type::text = ANY (ARRAY['auto'::character varying, 'manual'::character varying, 'correction'::character varying]::text[])),
  verification_method character varying CHECK (verification_method::text = ANY (ARRAY['fingerprint'::character varying, 'face'::character varying, 'rfid'::character varying, 'password'::character varying]::text[])),
  verification_quality integer CHECK (verification_quality >= 1 AND verification_quality <= 100),
  raw_log_data jsonb,
  sync_status character varying DEFAULT 'synced'::character varying CHECK (sync_status::text = ANY (ARRAY['pending'::character varying, 'synced'::character varying, 'failed'::character varying]::text[])),
  location_coordinates point,
  CONSTRAINT attendance_records_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_records_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT attendance_records_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.essl_devices(id)
);
CREATE TABLE public.audit_trail (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name character varying NOT NULL,
  record_id uuid NOT NULL,
  action USER-DEFINED NOT NULL,
  old_values jsonb,
  new_values jsonb,
  changed_fields ARRAY,
  user_id uuid,
  ip_address inet,
  user_agent text,
  timestamp timestamp without time zone DEFAULT now(),
  description text,
  CONSTRAINT audit_trail_pkey PRIMARY KEY (id),
  CONSTRAINT audit_trail_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.bank_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  account_number text,
  current_balance numeric DEFAULT 0,
  currency text DEFAULT 'USD'::text,
  account_type character varying DEFAULT 'BANK'::character varying CHECK (account_type::text = ANY (ARRAY['BANK'::character varying::text, 'UPI'::character varying::text, 'CASH'::character varying::text])),
  upi_id character varying,
  linked_bank_account_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT bank_accounts_linked_bank_account_id_fkey FOREIGN KEY (linked_bank_account_id) REFERENCES public.bank_accounts(id)
);
CREATE TABLE public.bank_reconciliations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bank_account_id uuid NOT NULL,
  statement_date date NOT NULL,
  statement_ending_balance numeric NOT NULL,
  book_ending_balance numeric NOT NULL,
  reconciled_balance numeric,
  status USER-DEFINED DEFAULT 'PENDING'::reconciliation_status,
  reconciled_by uuid,
  reconciled_at timestamp without time zone,
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT bank_reconciliations_pkey PRIMARY KEY (id),
  CONSTRAINT bank_reconciliations_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
  CONSTRAINT bank_reconciliations_reconciled_by_fkey FOREIGN KEY (reconciled_by) REFERENCES public.users(id)
);
CREATE TABLE public.bank_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bank_account_id uuid,
  date date NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['deposit'::text, 'withdrawal'::text])),
  amount numeric NOT NULL,
  description text,
  reference text,
  CONSTRAINT bank_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT bank_transactions_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id)
);
CREATE TABLE public.boms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  component text,
  quantity integer,
  CONSTRAINT boms_pkey PRIMARY KEY (id),
  CONSTRAINT boms_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.cashflow_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date,
  amount numeric,
  direction text CHECK (direction = ANY (ARRAY['inflow'::text, 'outflow'::text])),
  description text,
  reference_type text,
  reference_id uuid,
  CONSTRAINT cashflow_entries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cashflow_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  month date NOT NULL,
  inflows numeric NOT NULL,
  outflows numeric NOT NULL,
  net_position numeric NOT NULL,
  CONSTRAINT cashflow_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chart_of_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_code character varying NOT NULL UNIQUE,
  account_name character varying NOT NULL,
  account_type USER-DEFINED NOT NULL,
  account_subtype USER-DEFINED NOT NULL,
  parent_account_id uuid,
  description text,
  is_active boolean DEFAULT true,
  normal_balance text NOT NULL CHECK (normal_balance = ANY (ARRAY['DEBIT'::text, 'CREDIT'::text])),
  current_balance numeric DEFAULT 0,
  opening_balance numeric DEFAULT 0,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT chart_of_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT chart_of_accounts_parent_account_id_fkey FOREIGN KEY (parent_account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT chart_of_accounts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.chat_attachments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  message_id uuid,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_type character varying,
  file_size bigint,
  uploaded_by uuid,
  uploaded_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT chat_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT chat_attachments_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.chat_messages(id),
  CONSTRAINT chat_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  room_id uuid NOT NULL,
  sender_id uuid,
  message_text text,
  message_type character varying DEFAULT 'text'::character varying CHECK (message_type::text = ANY (ARRAY['text'::character varying, 'system'::character varying, 'file'::character varying, 'image'::character varying]::text[])),
  reply_to_id uuid,
  sent_at timestamp with time zone DEFAULT now(),
  edited_at timestamp with time zone,
  is_deleted boolean DEFAULT false,
  mentions jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  attachments jsonb DEFAULT '[]'::jsonb,
  reactions jsonb DEFAULT '[]'::jsonb,
  thread_id uuid,
  is_pinned boolean DEFAULT false,
  priority character varying DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id),
  CONSTRAINT chat_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id),
  CONSTRAINT chat_messages_reply_to_id_fkey FOREIGN KEY (reply_to_id) REFERENCES public.chat_messages(id)
);
CREATE TABLE public.chat_notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  room_id uuid NOT NULL,
  message_id uuid,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['mention'::character varying, 'new_message'::character varying, 'room_invite'::character varying]::text[])),
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT chat_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT chat_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT chat_notifications_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id),
  CONSTRAINT chat_notifications_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.chat_messages(id)
);
CREATE TABLE public.chat_participants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  room_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['purchaser'::character varying, 'salesperson'::character varying, 'warehouse_manager'::character varying, 'delivery_coordinator'::character varying, 'vendor'::character varying, 'admin'::character varying, 'employee'::character varying, 'manager'::character varying]::text[])),
  permissions jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  last_read_at timestamp with time zone DEFAULT now(),
  joined_at timestamp with time zone DEFAULT now(),
  left_at timestamp with time zone,
  notification_settings jsonb DEFAULT '{"mentions": true, "all_messages": false}'::jsonb,
  custom_name text,
  muted_until timestamp with time zone,
  CONSTRAINT chat_participants_pkey PRIMARY KEY (id),
  CONSTRAINT chat_participants_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id),
  CONSTRAINT chat_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.chat_rooms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  purchase_order_id uuid,
  sales_order_id uuid,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['purchase_order'::character varying, 'sales_order'::character varying, 'general'::character varying, 'employee_personal'::character varying, 'employee_group'::character varying, 'vendor_group'::character varying, 'vendor_personal'::character varying]::text[])),
  subject text NOT NULL,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'archived'::character varying, 'closed'::character varying]::text[])),
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  last_message_at timestamp with time zone DEFAULT now(),
  participant_count integer DEFAULT 0,
  is_archived boolean DEFAULT false,
  archived_at timestamp with time zone,
  archived_by uuid,
  CONSTRAINT chat_rooms_pkey PRIMARY KEY (id),
  CONSTRAINT chat_rooms_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT chat_rooms_sales_order_id_fkey FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id),
  CONSTRAINT chat_rooms_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT chat_rooms_archived_by_fkey FOREIGN KEY (archived_by) REFERENCES public.users(id)
);
CREATE TABLE public.custom_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  config_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  sku text,
  description text,
  price numeric DEFAULT 0,
  supplier_name text,
  supplier_id uuid,
  cost_price numeric,
  CONSTRAINT custom_products_pkey PRIMARY KEY (id),
  CONSTRAINT custom_products_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.customer_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  sales_rep_id uuid NOT NULL,
  assigned_date date NOT NULL DEFAULT CURRENT_DATE,
  is_active boolean NOT NULL DEFAULT true,
  assigned_by uuid NOT NULL,
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT customer_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT customer_assignments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_assignments_sales_rep_id_fkey FOREIGN KEY (sales_rep_id) REFERENCES public.users(id),
  CONSTRAINT customer_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id)
);
CREATE TABLE public.customer_complaints (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  sales_rep_id uuid,
  order_id uuid,
  complaint_type character varying NOT NULL CHECK (complaint_type::text = ANY (ARRAY['product'::character varying, 'service'::character varying, 'delivery'::character varying, 'billing'::character varying, 'other'::character varying]::text[])),
  subject character varying NOT NULL,
  description text NOT NULL,
  priority character varying NOT NULL DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying]::text[])),
  resolution text,
  resolved_by uuid,
  resolved_at timestamp without time zone,
  customer_satisfaction_rating integer CHECK (customer_satisfaction_rating >= 1 AND customer_satisfaction_rating <= 5),
  created_by uuid NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT customer_complaints_pkey PRIMARY KEY (id),
  CONSTRAINT customer_complaints_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_complaints_sales_rep_id_fkey FOREIGN KEY (sales_rep_id) REFERENCES public.users(id),
  CONSTRAINT customer_complaints_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.sales_orders(id),
  CONSTRAINT customer_complaints_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id),
  CONSTRAINT customer_complaints_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.customer_interactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid,
  type text,
  notes text,
  interaction_date timestamp without time zone,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  review_requested boolean DEFAULT false,
  review_given boolean DEFAULT false,
  review_rating integer CHECK (review_rating >= 1 AND review_rating <= 5),
  review_text text,
  review_requested_by uuid,
  review_requested_at timestamp with time zone,
  review_given_at timestamp with time zone,
  CONSTRAINT customer_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT customer_interactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT customer_interactions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_interactions_review_requested_by_fkey FOREIGN KEY (review_requested_by) REFERENCES public.users(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text UNIQUE,
  phone text,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  status text NOT NULL DEFAULT 'Lead'::text,
  source text NOT NULL DEFAULT 'Website'::text,
  tags ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  updated_at timestamp without time zone DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  updated_by uuid,
  address text,
  city character varying,
  state character varying,
  pincode character varying,
  notes text,
  latitude numeric,
  longitude numeric,
  geocoded_at timestamp with time zone,
  formatted_address text,
  floor text,
  assigned_sales_rep_id uuid,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_customers_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_customers_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT customers_assigned_sales_rep_id_fkey FOREIGN KEY (assigned_sales_rep_id) REFERENCES public.users(id)
);
CREATE TABLE public.daysheets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date NOT NULL UNIQUE,
  total_sales numeric DEFAULT 0,
  total_receipts numeric DEFAULT 0,
  total_expenses numeric DEFAULT 0,
  total_purchases numeric DEFAULT 0,
  cash_position numeric DEFAULT 0,
  bank_balance numeric DEFAULT 0,
  net_position numeric DEFAULT 0,
  is_closed boolean DEFAULT false,
  closed_by uuid,
  closed_at timestamp without time zone,
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT daysheets_pkey PRIMARY KEY (id),
  CONSTRAINT daysheets_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES public.users(id)
);
CREATE TABLE public.deliveries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sales_order_id uuid,
  driver_id uuid,
  status USER-DEFINED DEFAULT 'pending'::delivery_status,
  tracking_number text,
  updated_at timestamp without time zone DEFAULT now(),
  time_slot text,
  created_at timestamp without time zone DEFAULT now(),
  delivery_notes text,
  route_id uuid,
  sequence_order integer DEFAULT 1,
  delivery_address text,
  customer_name text,
  customer_phone text,
  latitude numeric,
  longitude numeric,
  items_count integer DEFAULT 1,
  estimated_delivery_time timestamp without time zone,
  actual_delivery_time timestamp without time zone,
  special_instructions text,
  signature_required boolean DEFAULT false,
  photo_required boolean DEFAULT false,
  delivery_fee numeric DEFAULT 0,
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'cod'::text])),
  delivered_to text,
  created_by uuid,
  delivery_type text DEFAULT 'full'::text CHECK (delivery_type = ANY (ARRAY['full'::text, 'partial'::text])),
  total_items integer DEFAULT 0,
  estimated_value numeric DEFAULT 0,
  driver_name text,
  CONSTRAINT deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT deliveries_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.users(id),
  CONSTRAINT deliveries_sales_order_id_fkey FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id),
  CONSTRAINT deliveries_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.delivery_routes(id)
);
CREATE TABLE public.delivery_cluster_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  delivery_id uuid NOT NULL,
  cluster_id uuid NOT NULL,
  distance_from_center_km numeric NOT NULL,
  assignment_score numeric DEFAULT 0.0,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT delivery_cluster_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_cluster_assignments_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES public.deliveries(id),
  CONSTRAINT delivery_cluster_assignments_cluster_id_fkey FOREIGN KEY (cluster_id) REFERENCES public.delivery_clusters(id)
);
CREATE TABLE public.delivery_clusters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  optimization_session_id uuid,
  cluster_number integer NOT NULL,
  center_latitude numeric NOT NULL,
  center_longitude numeric NOT NULL,
  radius_km numeric NOT NULL DEFAULT 5.0,
  total_deliveries integer NOT NULL DEFAULT 0,
  estimated_time_minutes integer NOT NULL DEFAULT 0,
  priority_score numeric DEFAULT 0.0,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT delivery_clusters_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_clusters_optimization_session_id_fkey FOREIGN KEY (optimization_session_id) REFERENCES public.route_optimization_sessions(id)
);
CREATE TABLE public.delivery_item_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  delivery_item_id uuid NOT NULL,
  old_status text,
  new_status text NOT NULL,
  status_changed_at timestamp without time zone DEFAULT now(),
  changed_by uuid,
  location_latitude numeric,
  location_longitude numeric,
  notes text,
  photo_url text,
  automatic_update boolean DEFAULT false,
  CONSTRAINT delivery_item_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_item_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id)
);
CREATE TABLE public.delivery_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  delivery_id uuid NOT NULL,
  sales_order_item_id uuid NOT NULL,
  product_id uuid,
  custom_product_id uuid,
  item_name text NOT NULL,
  quantity_to_deliver integer NOT NULL DEFAULT 1,
  quantity_delivered integer NOT NULL DEFAULT 0,
  quantity_remaining integer DEFAULT (quantity_to_deliver - quantity_delivered),
  unit_price numeric NOT NULL DEFAULT 0,
  total_value numeric DEFAULT ((quantity_to_deliver)::numeric * unit_price),
  item_status text NOT NULL DEFAULT 'pending'::text CHECK (item_status = ANY (ARRAY['pending'::text, 'loaded'::text, 'in_transit'::text, 'delivered'::text, 'failed'::text, 'damaged'::text, 'returned'::text])),
  item_description text,
  item_sku text,
  customer_id uuid,
  customer_name text,
  delivery_address text,
  customer_phone text,
  load_sequence integer DEFAULT 1,
  delivery_sequence integer DEFAULT 1,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT delivery_items_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_items_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT delivery_items_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES public.deliveries(id),
  CONSTRAINT delivery_items_sales_order_item_id_fkey FOREIGN KEY (sales_order_item_id) REFERENCES public.sales_order_items(id),
  CONSTRAINT delivery_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT delivery_items_custom_product_id_fkey FOREIGN KEY (custom_product_id) REFERENCES public.custom_products(id),
  CONSTRAINT delivery_items_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT delivery_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.delivery_items_backup (
  id uuid,
  delivery_id uuid,
  sales_order_item_id uuid,
  product_id uuid,
  custom_product_id uuid,
  item_name text,
  quantity_to_deliver integer,
  quantity_delivered integer,
  quantity_remaining integer,
  unit_price numeric,
  total_value numeric,
  item_status text,
  item_description text,
  item_image_url text,
  item_sku text,
  item_category text,
  item_dimensions text,
  item_weight numeric,
  special_handling_instructions text,
  loaded_at timestamp without time zone,
  delivered_at timestamp without time zone,
  delivery_proof_signature_url text,
  delivery_proof_photo_url text,
  delivered_to_person text,
  delivery_notes text,
  driver_notes text,
  damage_reported boolean,
  damage_description text,
  damage_photo_url text,
  customer_id uuid,
  customer_name text,
  delivery_address text,
  customer_phone text,
  load_sequence integer,
  delivery_sequence integer,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  created_by uuid,
  updated_by uuid,
  unit_weight numeric,
  total_weight numeric,
  optimization_priority integer,
  estimated_handling_time integer,
  verification_status text
);
CREATE TABLE public.delivery_proofs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  delivery_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['photo'::text, 'signature'::text])),
  url text NOT NULL,
  timestamp timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT delivery_proofs_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_proofs_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES public.deliveries(id)
);
CREATE TABLE public.delivery_route_waypoints (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  route_id uuid NOT NULL,
  sequence_order integer NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  waypoint_type text DEFAULT 'route'::text CHECK (waypoint_type = ANY (ARRAY['start'::text, 'route'::text, 'delivery'::text, 'end'::text])),
  delivery_id uuid,
  estimated_arrival timestamp without time zone,
  actual_arrival timestamp without time zone,
  stop_duration_minutes integer DEFAULT 30,
  priority_level integer DEFAULT 1,
  customer_availability_window_start time without time zone,
  customer_availability_window_end time without time zone,
  special_requirements text,
  items_to_deliver_count integer DEFAULT 0,
  total_weight_kg numeric DEFAULT 0.0,
  CONSTRAINT delivery_route_waypoints_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_route_waypoints_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.delivery_routes(id),
  CONSTRAINT delivery_route_waypoints_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES public.deliveries(id)
);
CREATE TABLE public.delivery_routes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  route_number text NOT NULL UNIQUE,
  driver_id uuid NOT NULL,
  truck_plate text,
  status text NOT NULL DEFAULT 'assigned'::text CHECK (status = ANY (ARRAY['assigned'::text, 'started'::text, 'in_transit'::text, 'paused'::text, 'completed'::text, 'cancelled'::text])),
  planned_start_time timestamp without time zone,
  actual_start_time timestamp without time zone,
  estimated_completion timestamp without time zone,
  actual_completion timestamp without time zone,
  total_items integer NOT NULL DEFAULT 0,
  total_deliveries integer NOT NULL DEFAULT 0,
  completed_deliveries integer NOT NULL DEFAULT 0,
  route_distance numeric DEFAULT 0,
  estimated_duration integer DEFAULT 0,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  notes text,
  truck_id uuid,
  max_capacity_items integer DEFAULT 100,
  current_load_items integer DEFAULT 0,
  max_capacity_weight numeric DEFAULT 1000.0,
  current_load_weight numeric DEFAULT 0.0,
  optimization_algorithm text DEFAULT 'distance_based'::text,
  route_efficiency_score numeric DEFAULT 0.0,
  fuel_estimated numeric DEFAULT 0.0,
  time_estimated integer DEFAULT 0,
  CONSTRAINT delivery_routes_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_routes_truck_id_fkey FOREIGN KEY (truck_id) REFERENCES public.trucks(id),
  CONSTRAINT delivery_routes_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.users(id),
  CONSTRAINT delivery_routes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.delivery_status_updates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  delivery_id uuid NOT NULL,
  old_status text,
  new_status text NOT NULL,
  updated_by uuid,
  updated_at timestamp without time zone DEFAULT now(),
  latitude numeric,
  longitude numeric,
  notes text,
  automatic boolean DEFAULT false,
  CONSTRAINT delivery_status_updates_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_status_updates_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES public.deliveries(id),
  CONSTRAINT delivery_status_updates_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.delivery_time_windows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  delivery_id uuid NOT NULL,
  preferred_start_time time without time zone NOT NULL,
  preferred_end_time time without time zone NOT NULL,
  earliest_acceptable_time time without time zone,
  latest_acceptable_time time without time zone,
  time_zone text DEFAULT 'UTC'::text,
  flexibility_minutes integer DEFAULT 0,
  premium_for_specific_time numeric DEFAULT 0.0,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT delivery_time_windows_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_time_windows_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES public.deliveries(id)
);
CREATE TABLE public.department_policies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  department character varying NOT NULL,
  policy_id uuid NOT NULL,
  effective_from date NOT NULL,
  effective_to date,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT department_policies_pkey PRIMARY KEY (id),
  CONSTRAINT department_policies_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.attendance_policies(id)
);
CREATE TABLE public.device_sync_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL,
  sync_type character varying NOT NULL CHECK (sync_type::text = ANY (ARRAY['attendance'::character varying, 'employee'::character varying, 'full'::character varying]::text[])),
  sync_status character varying NOT NULL CHECK (sync_status::text = ANY (ARRAY['started'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  records_synced integer DEFAULT 0,
  sync_duration integer,
  error_message text,
  sync_timestamp timestamp without time zone DEFAULT now(),
  CONSTRAINT device_sync_logs_pkey PRIMARY KEY (id),
  CONSTRAINT device_sync_logs_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.essl_devices(id)
);
CREATE TABLE public.driver_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  route_id uuid,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  accuracy numeric,
  speed numeric DEFAULT 0,
  heading numeric DEFAULT 0,
  battery_level integer,
  timestamp timestamp without time zone DEFAULT now(),
  location_type text DEFAULT 'tracking'::text CHECK (location_type = ANY (ARRAY['tracking'::text, 'delivery_start'::text, 'delivery_complete'::text, 'break_start'::text, 'break_end'::text])),
  CONSTRAINT driver_locations_pkey PRIMARY KEY (id),
  CONSTRAINT driver_locations_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.users(id),
  CONSTRAINT driver_locations_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.delivery_routes(id)
);
CREATE TABLE public.driver_performance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  date date NOT NULL,
  total_routes integer DEFAULT 0,
  completed_routes integer DEFAULT 0,
  total_deliveries integer DEFAULT 0,
  successful_deliveries integer DEFAULT 0,
  failed_deliveries integer DEFAULT 0,
  total_distance numeric DEFAULT 0,
  total_time integer DEFAULT 0,
  on_time_deliveries integer DEFAULT 0,
  late_deliveries integer DEFAULT 0,
  average_delivery_time numeric DEFAULT 0,
  fuel_consumption numeric DEFAULT 0,
  customer_rating numeric DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT driver_performance_pkey PRIMARY KEY (id),
  CONSTRAINT driver_performance_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.users(id)
);
CREATE TABLE public.employee_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  document_type text NOT NULL,
  document_name text NOT NULL,
  file_url text NOT NULL,
  expiry_date date,
  is_verified boolean DEFAULT false,
  verified_by uuid,
  verified_at timestamp without time zone,
  uploaded_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT employee_documents_pkey PRIMARY KEY (id),
  CONSTRAINT employee_documents_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id),
  CONSTRAINT employee_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.employee_leave_balances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  leave_type_id uuid NOT NULL,
  year integer NOT NULL,
  allocated_days numeric DEFAULT 0,
  used_days numeric DEFAULT 0,
  remaining_days numeric DEFAULT 0,
  carry_forward_days numeric DEFAULT 0,
  CONSTRAINT employee_leave_balances_pkey PRIMARY KEY (id),
  CONSTRAINT employee_leave_balances_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_leave_balances_leave_type_id_fkey FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id)
);
CREATE TABLE public.employee_shifts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  shift_id uuid NOT NULL,
  effective_from date NOT NULL,
  effective_to date,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT employee_shifts_pkey PRIMARY KEY (id),
  CONSTRAINT employee_shifts_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_shifts_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.work_shifts(id)
);
CREATE TABLE public.employee_trainings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  training_program_id uuid NOT NULL,
  enrollment_date date,
  start_date date,
  completion_date date,
  status text DEFAULT 'enrolled'::text CHECK (status = ANY (ARRAY['enrolled'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  score numeric,
  feedback text,
  certificate_url text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT employee_trainings_pkey PRIMARY KEY (id),
  CONSTRAINT employee_trainings_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_trainings_training_program_id_fkey FOREIGN KEY (training_program_id) REFERENCES public.training_programs(id)
);
CREATE TABLE public.employees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text,
  email text,
  position text,
  salary numeric,
  created_at timestamp without time zone DEFAULT now(),
  user_id uuid,
  employee_id text UNIQUE,
  department text,
  hire_date date,
  employment_type text CHECK (employment_type = ANY (ARRAY['full_time'::text, 'part_time'::text, 'contract'::text, 'intern'::text])),
  employment_status text DEFAULT 'active'::text CHECK (employment_status = ANY (ARRAY['active'::text, 'inactive'::text, 'terminated'::text, 'on_leave'::text])),
  phone text,
  address text,
  emergency_contact_name text,
  emergency_contact_phone text,
  date_of_birth date,
  gender text,
  nationality text,
  marital_status text,
  manager_id uuid,
  updated_at timestamp without time zone DEFAULT now(),
  updated_by uuid,
  essl_device_id character varying,
  biometric_template bytea,
  rfid_card_number character varying,
  face_template bytea,
  enrollment_status character varying DEFAULT 'pending'::character varying CHECK (enrollment_status::text = ANY (ARRAY['pending'::character varying, 'enrolled'::character varying, 'failed'::character varying, 'disabled'::character varying]::text[])),
  enrollment_date timestamp without time zone,
  last_sync_date timestamp without time zone,
  CONSTRAINT employees_pkey PRIMARY KEY (id),
  CONSTRAINT employees_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT employees_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.employees(id),
  CONSTRAINT employees_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.essl_devices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_name character varying NOT NULL,
  device_serial character varying NOT NULL UNIQUE,
  ip_address inet NOT NULL,
  port integer DEFAULT 4370,
  location character varying,
  device_type character varying DEFAULT 'fingerprint'::character varying CHECK (device_type::text = ANY (ARRAY['fingerprint'::character varying, 'face'::character varying, 'rfid'::character varying, 'hybrid'::character varying]::text[])),
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'maintenance'::character varying]::text[])),
  last_connected timestamp without time zone,
  total_capacity integer DEFAULT 1000,
  enrolled_users integer DEFAULT 0,
  firmware_version character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT essl_devices_pkey PRIMARY KEY (id)
);
CREATE TABLE public.expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['Raw Materials'::text, 'Direct Labor'::text, 'Manufacturing Overhead'::text, 'Administrative'::text, 'Salaries & Benefits'::text, 'Marketing & Sales'::text, 'Logistics & Distribution'::text, 'Technology'::text, 'Insurance'::text, 'Maintenance & Repairs'::text, 'Travel & Entertainment'::text, 'Research & Development'::text, 'Miscellaneous'::text, 'Vehicle Fleet'::text, 'Accounts Payable'::text, 'Prepaid Expenses'::text, 'Rent'::text, 'Utilities'::text, 'Salaries'::text, 'Marketing'::text, 'Other'::text, 'Manufacturing'::text, 'Production'::text, 'Maintenance'::text, 'Administration'::text, 'Logistics'::text])),
  description text,
  amount numeric NOT NULL,
  payment_method text,
  created_by uuid,
  type text CHECK (type = ANY (ARRAY['Direct'::text, 'Indirect'::text, 'Fixed'::text, 'Variable'::text])),
  subcategory text,
  entity_type text CHECK (entity_type = ANY (ARRAY['truck'::text, 'employee'::text, 'supplier'::text])),
  entity_id uuid,
  entity_reference_id uuid,
  updated_at timestamp without time zone DEFAULT now(),
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT expenses_pkey PRIMARY KEY (id),
  CONSTRAINT expenses_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.general_ledger (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid NOT NULL,
  journal_entry_id uuid NOT NULL,
  journal_line_id uuid NOT NULL,
  transaction_date date NOT NULL,
  posting_date date NOT NULL,
  description text NOT NULL,
  reference character varying,
  debit_amount numeric DEFAULT 0,
  credit_amount numeric DEFAULT 0,
  running_balance numeric NOT NULL,
  source_document_type character varying,
  source_document_id uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT general_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT general_ledger_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT general_ledger_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
  CONSTRAINT general_ledger_journal_line_id_fkey FOREIGN KEY (journal_line_id) REFERENCES public.journal_entry_lines(id)
);
CREATE TABLE public.holidays (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  holiday_name character varying NOT NULL,
  holiday_date date NOT NULL,
  holiday_type character varying DEFAULT 'public'::character varying CHECK (holiday_type::text = ANY (ARRAY['public'::character varying, 'company'::character varying, 'optional'::character varying]::text[])),
  is_active boolean DEFAULT true,
  description text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT holidays_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hr_policies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  policy_name text NOT NULL,
  policy_document_url text,
  version text,
  effective_date date,
  expiry_date date,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT hr_policies_pkey PRIMARY KEY (id),
  CONSTRAINT hr_policies_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.inventory_count_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  product_id uuid NOT NULL,
  sku text NOT NULL,
  product_name text NOT NULL,
  counted_quantity integer NOT NULL DEFAULT 0,
  previous_quantity integer DEFAULT 0,
  variance integer DEFAULT 0,
  notes text,
  scanned_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_count_entries_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_count_entries_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.inventory_count_jobs(id),
  CONSTRAINT inventory_count_entries_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.inventory_count_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  status text NOT NULL,
  counted_items jsonb,
  total_items integer,
  counted_count integer,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  final_counted_items integer,
  uncounted_items_zeroed integer,
  CONSTRAINT inventory_count_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_count_jobs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.inventory_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  category text,
  subcategory text,
  material text,
  location text,
  quantity integer NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  reorder_point integer NOT NULL DEFAULT 0,
  supplier_id uuid,
  updated_at timestamp without time zone DEFAULT now(),
  qr_code_url text,
  CONSTRAINT inventory_items_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT inventory_items_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.investment_categories (
  id integer NOT NULL DEFAULT nextval('investment_categories_id_seq'::regclass),
  category_name character varying NOT NULL UNIQUE,
  description text,
  chart_account_code character varying DEFAULT '3100'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT investment_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.investments (
  id integer NOT NULL DEFAULT nextval('investments_id_seq'::regclass),
  partner_id integer,
  category_id integer,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  investment_date date NOT NULL DEFAULT CURRENT_DATE,
  description text,
  payment_method character varying NOT NULL DEFAULT 'cash'::character varying,
  bank_account_id uuid,
  reference_number character varying,
  upi_reference character varying,
  notes text,
  journal_entry_id uuid,
  created_by character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT investments_pkey PRIMARY KEY (id),
  CONSTRAINT investments_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT investments_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.investment_categories(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sales_order_id uuid,
  total numeric,
  status USER-DEFINED DEFAULT 'unpaid'::invoice_status,
  created_at timestamp without time zone DEFAULT now(),
  customer_id uuid,
  paid_amount numeric DEFAULT 0,
  customer_name text,
  waived_amount numeric DEFAULT 0,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.journal_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  journal_number character varying NOT NULL UNIQUE,
  entry_date date NOT NULL,
  posting_date date,
  reference_number character varying,
  description text NOT NULL,
  entry_type USER-DEFINED DEFAULT 'STANDARD'::journal_entry_type,
  status USER-DEFINED DEFAULT 'DRAFT'::journal_status,
  total_debit numeric NOT NULL DEFAULT 0,
  total_credit numeric NOT NULL DEFAULT 0,
  source_document_type character varying,
  source_document_id uuid,
  created_by uuid NOT NULL,
  posted_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  posted_at timestamp without time zone,
  notes text,
  updated_by uuid,
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT journal_entries_pkey PRIMARY KEY (id),
  CONSTRAINT journal_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT journal_entries_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES public.users(id)
);
CREATE TABLE public.journal_entry_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  journal_entry_id uuid NOT NULL,
  line_number integer NOT NULL,
  account_id uuid NOT NULL,
  description text,
  debit_amount numeric DEFAULT 0,
  credit_amount numeric DEFAULT 0,
  reference character varying,
  updated_at timestamp without time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT journal_entry_lines_pkey PRIMARY KEY (id),
  CONSTRAINT journal_entry_lines_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
  CONSTRAINT journal_entry_lines_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.journal_entry_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_name character varying NOT NULL,
  template_code character varying NOT NULL UNIQUE,
  description text,
  source_document_type character varying NOT NULL,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT journal_entry_templates_pkey PRIMARY KEY (id),
  CONSTRAINT journal_entry_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.leave_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  leave_type_id uuid NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  total_days numeric NOT NULL,
  reason text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text])),
  applied_date timestamp without time zone DEFAULT now(),
  approved_by uuid,
  approved_date timestamp without time zone,
  rejection_reason text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT leave_requests_pkey PRIMARY KEY (id),
  CONSTRAINT leave_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT leave_requests_leave_type_id_fkey FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id),
  CONSTRAINT leave_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.leave_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  max_days_per_year integer,
  carry_forward_allowed boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT leave_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.opening_balances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid,
  entity_type text CHECK (entity_type = ANY (ARRAY['customer'::text, 'supplier'::text, 'inventory'::text, 'bank'::text])),
  entity_id uuid,
  opening_date date NOT NULL,
  debit_amount numeric DEFAULT 0,
  credit_amount numeric DEFAULT 0,
  fiscal_year integer,
  period_id uuid,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT opening_balances_pkey PRIMARY KEY (id),
  CONSTRAINT opening_balances_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT opening_balances_period_id_fkey FOREIGN KEY (period_id) REFERENCES public.accounting_periods(id),
  CONSTRAINT opening_balances_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.order_modifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid,
  modification_type character varying CHECK (modification_type::text = ANY (ARRAY['add'::character varying, 'remove'::character varying, 'modify'::character varying]::text[])),
  previous_state json,
  new_state json,
  reason text,
  approved_by uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT order_modifications_pkey PRIMARY KEY (id),
  CONSTRAINT order_modifications_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.sales_orders(id),
  CONSTRAINT order_modifications_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.partial_delivery_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sales_order_id uuid NOT NULL,
  original_delivery_date date,
  total_items integer NOT NULL DEFAULT 0,
  delivered_items integer NOT NULL DEFAULT 0,
  remaining_items integer DEFAULT (total_items - delivered_items),
  delivery_completion_percentage numeric DEFAULT 
CASE
    WHEN (total_items = 0) THEN (0)::numeric
    ELSE round((((delivered_items)::numeric / (total_items)::numeric) * (100)::numeric), 2)
END,
  status text NOT NULL DEFAULT 'partial'::text CHECK (status = ANY (ARRAY['pending'::text, 'partial'::text, 'completed'::text, 'cancelled'::text])),
  next_delivery_scheduled date,
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT partial_delivery_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT partial_delivery_tracking_sales_order_id_fkey FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id)
);
CREATE TABLE public.partners (
  id integer NOT NULL DEFAULT nextval('partners_id_seq'::regclass),
  name character varying NOT NULL,
  email character varying UNIQUE,
  phone character varying,
  partner_type character varying NOT NULL DEFAULT 'partner'::character varying,
  initial_investment numeric DEFAULT 0,
  equity_percentage numeric DEFAULT 0 CHECK (equity_percentage >= 0::numeric AND equity_percentage <= 100::numeric),
  is_active boolean DEFAULT true,
  notes text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT partners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid,
  amount numeric,
  payment_date timestamp without time zone,
  date date DEFAULT now(),
  method text,
  reference text,
  description text,
  bank_account_id uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT payments_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id)
);
CREATE TABLE public.payroll_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  salary_structure_id uuid,
  pay_period_start date NOT NULL,
  pay_period_end date NOT NULL,
  basic_salary numeric,
  total_allowances numeric,
  total_deductions numeric,
  gross_salary numeric,
  net_salary numeric,
  working_days integer,
  present_days integer,
  leave_days integer,
  overtime_hours numeric DEFAULT 0,
  overtime_amount numeric DEFAULT 0,
  bonus numeric DEFAULT 0,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'processed'::text, 'paid'::text])),
  processed_by uuid,
  processed_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT payroll_records_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_records_salary_structure_id_fkey FOREIGN KEY (salary_structure_id) REFERENCES public.salary_structures(id),
  CONSTRAINT payroll_records_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.users(id),
  CONSTRAINT payroll_records_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.performance_goals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  goal_title text NOT NULL,
  description text,
  target_date date,
  weightage numeric DEFAULT 0,
  status text DEFAULT 'not_started'::text CHECK (status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'completed'::text, 'overdue'::text])),
  achievement_percentage numeric DEFAULT 0,
  manager_rating integer CHECK (manager_rating >= 1 AND manager_rating <= 5),
  self_rating integer CHECK (self_rating >= 1 AND self_rating <= 5),
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT performance_goals_pkey PRIMARY KEY (id),
  CONSTRAINT performance_goals_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT performance_goals_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.performance_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid,
  reviewer_id uuid,
  score integer,
  feedback text,
  review_date timestamp without time zone,
  review_period_start date,
  review_period_end date,
  review_type text CHECK (review_type = ANY (ARRAY['annual'::text, 'mid_year'::text, 'probation'::text, 'project_based'::text])),
  goals_achievement jsonb DEFAULT '{}'::jsonb,
  strengths text,
  areas_for_improvement text,
  development_plan text,
  manager_comments text,
  employee_comments text,
  hr_comments text,
  overall_rating text CHECK (overall_rating = ANY (ARRAY['excellent'::text, 'good'::text, 'satisfactory'::text, 'needs_improvement'::text, 'unsatisfactory'::text])),
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'reviewed'::text, 'approved'::text])),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT performance_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT performance_reviews_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT performance_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id)
);
CREATE TABLE public.permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.policy_acknowledgments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  policy_id uuid NOT NULL,
  acknowledged_at timestamp without time zone DEFAULT now(),
  digital_signature text,
  CONSTRAINT policy_acknowledgments_pkey PRIMARY KEY (id),
  CONSTRAINT policy_acknowledgments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT policy_acknowledgments_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.hr_policies(id)
);
CREATE TABLE public.production_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  work_order_id uuid,
  log_date date NOT NULL,
  output_quantity integer NOT NULL DEFAULT 0,
  defects integer NOT NULL DEFAULT 0,
  downtime_hours numeric DEFAULT 0,
  efficiency_percentage numeric DEFAULT 0,
  quality_score numeric DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT production_logs_pkey PRIMARY KEY (id),
  CONSTRAINT production_logs_work_order_id_fkey FOREIGN KEY (work_order_id) REFERENCES public.work_orders(id),
  CONSTRAINT production_logs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  sku text UNIQUE,
  description text,
  category text,
  price numeric,
  created_at timestamp without time zone DEFAULT now(),
  image_url text,
  supplier_id uuid,
  updated_at timestamp without time zone DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  created_by uuid,
  updated_by uuid,
  config_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
  cost numeric,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT fk_products_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_products_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.profit_margins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  margin_percentage numeric NOT NULL,
  product_id uuid,
  category text,
  subcategory text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profit_margins_pkey PRIMARY KEY (id),
  CONSTRAINT profit_margins_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.purchase_order_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_order_id uuid NOT NULL,
  url text NOT NULL,
  uploaded_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT purchase_order_images_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_images_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id)
);
CREATE TABLE public.purchase_order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  purchase_order_id uuid NOT NULL,
  sales_order_item_id uuid,
  quote_custom_item_id uuid,
  item_name text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0,
  total_price numeric DEFAULT ((quantity)::numeric * unit_price),
  specifications text,
  materials jsonb,
  dimensions text,
  finish text,
  color text,
  custom_instructions text,
  base_product_name text,
  image_url text,
  supplier_id uuid,
  supplier_name text,
  item_type text NOT NULL DEFAULT 'regular'::text CHECK (item_type = ANY (ARRAY['regular'::text, 'custom'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT purchase_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_items_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT purchase_order_items_sales_order_item_id_fkey FOREIGN KEY (sales_order_item_id) REFERENCES public.sales_order_items(id),
  CONSTRAINT purchase_order_items_quote_custom_item_id_fkey FOREIGN KEY (quote_custom_item_id) REFERENCES public.quote_custom_items(id),
  CONSTRAINT purchase_order_items_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.purchase_order_materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_order_id uuid NOT NULL,
  material text NOT NULL,
  CONSTRAINT purchase_order_materials_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_materials_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id)
);
CREATE TABLE public.purchase_order_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_order_id uuid,
  amount numeric,
  payment_date timestamp without time zone DEFAULT now(),
  payment_method text DEFAULT 'cash'::text,
  reference_number text,
  notes text,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  status text DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  bank_account_id uuid,
  CONSTRAINT purchase_order_payments_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_payments_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT purchase_order_payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT purchase_order_payments_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id)
);
CREATE TABLE public.purchase_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid,
  product_id uuid,
  quantity integer,
  status USER-DEFINED DEFAULT 'pending'::purchase_order_status,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  is_custom boolean NOT NULL DEFAULT false,
  custom_type text,
  description text,
  total numeric,
  due_date date,
  payment_status USER-DEFINED DEFAULT 'unpaid'::payment_status,
  paid_amount numeric DEFAULT 0,
  product_name text,
  sales_order_id uuid,
  CONSTRAINT purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT purchase_orders_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT purchase_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.quote_custom_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  name text NOT NULL,
  quantity integer NOT NULL,
  unit_price numeric NOT NULL,
  configuration jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  product_id uuid,
  supplier_id uuid,
  supplier_name text,
  image_url text,
  discount_percentage numeric DEFAULT 0,
  item_type text DEFAULT 'custom'::text CHECK (item_type = ANY (ARRAY['custom'::text, 'new'::text, 'customized_existing'::text])),
  base_product_name text,
  specifications text,
  materials jsonb DEFAULT '[]'::jsonb,
  dimensions text,
  finish text,
  color text,
  custom_instructions text,
  estimated_delivery_days integer DEFAULT 30,
  complexity_level text DEFAULT 'medium'::text CHECK (complexity_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_production'::text, 'ready'::text, 'delivered'::text])),
  notes text,
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT quote_custom_items_pkey PRIMARY KEY (id),
  CONSTRAINT quote_custom_items_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT quote_custom_items_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.quotes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid,
  items jsonb,
  total_price numeric,
  status text DEFAULT 'Draft'::text,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  customer text,
  discount_amount numeric DEFAULT 0,
  emi_enabled boolean DEFAULT false,
  emi_plan jsonb,
  emi_monthly numeric DEFAULT 0,
  original_price numeric DEFAULT 0,
  final_price numeric DEFAULT 0,
  notes text,
  bajaj_finance_amount numeric,
  freight_charges numeric,
  bajaj_approved_amount numeric,
  bajaj_processing_fee_rate numeric DEFAULT 8.00,
  bajaj_processing_fee_amount numeric DEFAULT 0,
  bajaj_convenience_charges numeric DEFAULT 0,
  bajaj_total_customer_payment numeric DEFAULT 0,
  bajaj_merchant_receivable numeric DEFAULT 0,
  tax_percentage numeric DEFAULT 18.00,
  tax_amount numeric DEFAULT 0,
  taxable_amount numeric DEFAULT 0,
  grand_total numeric DEFAULT 0,
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT quotes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.receipt_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  goods_receipt_id uuid NOT NULL,
  image_url text NOT NULL,
  image_type text DEFAULT 'condition'::text CHECK (image_type = ANY (ARRAY['condition'::text, 'defect'::text, 'packaging'::text, 'label'::text])),
  description text,
  uploaded_at timestamp without time zone DEFAULT now(),
  CONSTRAINT receipt_images_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reconciliation_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reconciliation_id uuid,
  transaction_id uuid,
  transaction_type character varying,
  description text NOT NULL,
  amount numeric NOT NULL,
  item_type character varying CHECK (item_type::text = ANY (ARRAY['OUTSTANDING_CHECK'::character varying, 'DEPOSIT_IN_TRANSIT'::character varying, 'BANK_FEE'::character varying, 'INTEREST'::character varying, 'ERROR'::character varying, 'OTHER'::character varying]::text[])),
  is_cleared boolean DEFAULT false,
  cleared_date date,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT reconciliation_items_pkey PRIMARY KEY (id),
  CONSTRAINT reconciliation_items_reconciliation_id_fkey FOREIGN KEY (reconciliation_id) REFERENCES public.bank_reconciliations(id)
);
CREATE TABLE public.return_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  return_id uuid,
  product_id uuid,
  quantity integer,
  condition_notes text,
  refund_amount numeric,
  resolution character varying CHECK (resolution::text = ANY (ARRAY['refund'::character varying, 'replace'::character varying, 'repair'::character varying]::text[])),
  status character varying DEFAULT 'pending'::character varying,
  sales_order_item_id uuid,
  unit_price numeric DEFAULT 0,
  is_custom_product boolean DEFAULT false,
  custom_product_id uuid,
  CONSTRAINT return_items_pkey PRIMARY KEY (id),
  CONSTRAINT return_items_return_id_fkey FOREIGN KEY (return_id) REFERENCES public.returns(id),
  CONSTRAINT return_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT return_items_sales_order_item_id_fkey FOREIGN KEY (sales_order_item_id) REFERENCES public.sales_order_items(id),
  CONSTRAINT return_items_custom_product_id_fkey FOREIGN KEY (custom_product_id) REFERENCES public.custom_products(id)
);
CREATE TABLE public.returns (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid,
  return_type character varying CHECK (return_type::text = ANY (ARRAY['return'::character varying::text, 'warranty'::character varying::text, 'complaint'::character varying::text, 'exchange'::character varying::text])),
  status character varying DEFAULT 'pending'::character varying,
  reason text,
  images json,
  inspection_notes text,
  approved_by uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  sales_representative_id uuid,
  return_value numeric DEFAULT 0,
  cost_value numeric DEFAULT 0,
  created_by uuid,
  CONSTRAINT returns_pkey PRIMARY KEY (id),
  CONSTRAINT returns_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.sales_orders(id),
  CONSTRAINT returns_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT returns_sales_representative_id_fkey FOREIGN KEY (sales_representative_id) REFERENCES public.users(id),
  CONSTRAINT returns_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.risk_incidents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type text NOT NULL,
  description text,
  severity text CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  status text CHECK (status = ANY (ARRAY['open'::text, 'investigating'::text, 'resolved'::text, 'closed'::text])),
  reported_date date DEFAULT CURRENT_DATE,
  resolved_date date,
  impact_cost numeric DEFAULT 0,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT risk_incidents_pkey PRIMARY KEY (id),
  CONSTRAINT risk_incidents_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.rma_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  return_id uuid NOT NULL,
  rma_number text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'completed'::text])),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  notes text,
  processed_by uuid,
  CONSTRAINT rma_requests_pkey PRIMARY KEY (id),
  CONSTRAINT rma_requests_return_id_fkey FOREIGN KEY (return_id) REFERENCES public.returns(id),
  CONSTRAINT rma_requests_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.users(id)
);
CREATE TABLE public.role_permissions (
  role_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  CONSTRAINT role_permissions_pkey PRIMARY KEY (permission_id, role_id),
  CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.route_constraints (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  route_id uuid,
  constraint_type text NOT NULL CHECK (constraint_type = ANY (ARRAY['time_window'::text, 'capacity'::text, 'driver_availability'::text, 'vehicle_restriction'::text, 'customer_preference'::text])),
  constraint_value jsonb NOT NULL DEFAULT '{}'::jsonb,
  priority integer DEFAULT 1,
  is_hard_constraint boolean DEFAULT false,
  violation_penalty numeric DEFAULT 0.0,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT route_constraints_pkey PRIMARY KEY (id),
  CONSTRAINT route_constraints_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.delivery_routes(id)
);
CREATE TABLE public.route_optimization_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_name text NOT NULL,
  optimization_date date NOT NULL DEFAULT CURRENT_DATE,
  total_orders integer NOT NULL DEFAULT 0,
  total_items integer NOT NULL DEFAULT 0,
  total_routes_generated integer NOT NULL DEFAULT 0,
  optimization_algorithm text NOT NULL DEFAULT 'distance_based'::text,
  parameters jsonb DEFAULT '{}'::jsonb,
  efficiency_score numeric DEFAULT 0.0,
  estimated_fuel_savings numeric DEFAULT 0.0,
  estimated_time_savings integer DEFAULT 0,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  completed_at timestamp without time zone,
  CONSTRAINT route_optimization_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT route_optimization_sessions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.salary_structures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  basic_salary numeric NOT NULL,
  house_rent_allowance numeric DEFAULT 0,
  transport_allowance numeric DEFAULT 0,
  medical_allowance numeric DEFAULT 0,
  other_allowances jsonb DEFAULT '{}'::jsonb,
  provident_fund_deduction numeric DEFAULT 0,
  tax_deduction numeric DEFAULT 0,
  other_deductions jsonb DEFAULT '{}'::jsonb,
  effective_from date NOT NULL,
  effective_to date,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT salary_structures_pkey PRIMARY KEY (id),
  CONSTRAINT salary_structures_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT salary_structures_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.sales_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  product_id uuid,
  quantity integer NOT NULL,
  unit_price numeric NOT NULL,
  discount_percentage numeric DEFAULT 0,
  custom_product_id uuid,
  name text,
  supplier_name text,
  supplier_id uuid,
  final_price numeric,
  cost numeric DEFAULT 0,
  image_url text,
  tax_percentage numeric DEFAULT 18.00,
  tax_amount numeric DEFAULT 0,
  taxable_amount numeric DEFAULT 0,
  CONSTRAINT sales_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT sales_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT sales_order_items_custom_product_id_fkey FOREIGN KEY (custom_product_id) REFERENCES public.custom_products(id),
  CONSTRAINT sales_order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.sales_orders(id)
);
CREATE TABLE public.sales_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid,
  customer_id uuid,
  status USER-DEFINED DEFAULT 'draft'::sales_order_status,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  updated_by uuid,
  po_created boolean DEFAULT false,
  address text,
  expected_delivery_date date,
  notes text,
  final_price numeric,
  original_price numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  emi_enabled boolean DEFAULT false,
  emi_plan jsonb DEFAULT '{}'::jsonb,
  emi_monthly numeric DEFAULT 0,
  bajaj_finance_amount numeric DEFAULT 0,
  freight_charges numeric DEFAULT 0,
  sales_representative_id uuid,
  waived_amount numeric DEFAULT 0,
  delivery_floor character varying DEFAULT 'ground'::character varying,
  first_floor_awareness boolean DEFAULT false,
  bajaj_processing_fee_rate numeric DEFAULT 8.00,
  bajaj_processing_fee_amount numeric DEFAULT 0,
  bajaj_convenience_charges numeric DEFAULT 0,
  bajaj_total_customer_payment numeric DEFAULT 0,
  bajaj_merchant_receivable numeric DEFAULT 0,
  tax_percentage numeric DEFAULT 18.00,
  tax_amount numeric DEFAULT 0,
  taxable_amount numeric DEFAULT 0,
  grand_total numeric DEFAULT 0,
  CONSTRAINT sales_orders_pkey PRIMARY KEY (id),
  CONSTRAINT sales_orders_sales_representative_id_fkey FOREIGN KEY (sales_representative_id) REFERENCES public.users(id),
  CONSTRAINT sales_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT sales_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_sales_orders_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_sales_orders_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT sales_orders_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.sales_performance_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sales_rep_id uuid NOT NULL,
  metric_period_start date NOT NULL,
  metric_period_end date NOT NULL,
  period_type character varying NOT NULL CHECK (period_type::text = ANY (ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying, 'quarterly'::character varying, 'yearly'::character varying]::text[])),
  total_revenue numeric NOT NULL DEFAULT 0,
  total_orders integer NOT NULL DEFAULT 0,
  total_customers integer NOT NULL DEFAULT 0,
  new_customers integer NOT NULL DEFAULT 0,
  customer_retention_rate numeric NOT NULL DEFAULT 0,
  average_order_value numeric NOT NULL DEFAULT 0,
  conversion_rate numeric NOT NULL DEFAULT 0,
  target_achievement_percentage numeric NOT NULL DEFAULT 0,
  ranking_position integer,
  ranking_total integer,
  last_calculated timestamp without time zone DEFAULT now(),
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT sales_performance_cache_pkey PRIMARY KEY (id),
  CONSTRAINT sales_performance_cache_sales_rep_id_fkey FOREIGN KEY (sales_rep_id) REFERENCES public.users(id)
);
CREATE TABLE public.sales_targets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sales_rep_id uuid NOT NULL,
  target_period_start date NOT NULL,
  target_period_end date NOT NULL,
  target_type character varying NOT NULL CHECK (target_type::text = ANY (ARRAY['monthly'::character varying, 'quarterly'::character varying, 'yearly'::character varying]::text[])),
  revenue_target numeric NOT NULL DEFAULT 0,
  orders_target integer NOT NULL DEFAULT 0,
  customers_target integer NOT NULL DEFAULT 0,
  achievement_revenue numeric NOT NULL DEFAULT 0,
  achievement_orders integer NOT NULL DEFAULT 0,
  achievement_customers integer NOT NULL DEFAULT 0,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  created_by uuid NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT sales_targets_pkey PRIMARY KEY (id),
  CONSTRAINT sales_targets_sales_rep_id_fkey FOREIGN KEY (sales_rep_id) REFERENCES public.users(id),
  CONSTRAINT sales_targets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.settings (
  key text NOT NULL,
  value text NOT NULL,
  description text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT settings_pkey PRIMARY KEY (key)
);
CREATE TABLE public.stock_adjustments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  inventory_item_id uuid NOT NULL,
  adjustment_type character varying NOT NULL CHECK (adjustment_type::text = ANY (ARRAY['count'::character varying, 'sale'::character varying, 'damage'::character varying, 'return'::character varying, 'transfer'::character varying, 'received'::character varying, 'found'::character varying, 'theft'::character varying]::text[])),
  quantity_before integer NOT NULL DEFAULT 0,
  quantity_after integer NOT NULL DEFAULT 0,
  quantity_change integer DEFAULT (quantity_after - quantity_before),
  reason text NOT NULL,
  notes text,
  adjusted_by uuid,
  adjusted_at timestamp without time zone DEFAULT now(),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT stock_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT stock_adjustments_inventory_item_id_fkey FOREIGN KEY (inventory_item_id) REFERENCES public.inventory_items(id),
  CONSTRAINT stock_adjustments_adjusted_by_fkey FOREIGN KEY (adjusted_by) REFERENCES public.users(id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text,
  contact text,
  updated_at timestamp without time zone DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  address text,
  email text,
  CONSTRAINT suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT fk_suppliers_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_suppliers_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title character varying NOT NULL,
  description text NOT NULL,
  status character varying DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying]::text[])),
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  category character varying,
  assigned_to uuid,
  resolution_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT support_tickets_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  assigned_to uuid,
  status text CHECK (status = ANY (ARRAY['To Do'::text, 'In Progress'::text, 'Done'::text, 'Cancelled'::text])),
  priority text CHECK (priority = ANY (ARRAY['Low'::text, 'Medium'::text, 'High'::text, 'Critical'::text])),
  due_date date,
  completed_date date,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.employees(id),
  CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.tax_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tax_code character varying NOT NULL UNIQUE,
  tax_name character varying NOT NULL,
  tax_type USER-DEFINED NOT NULL,
  tax_rate numeric NOT NULL,
  description text,
  account_id uuid,
  is_active boolean DEFAULT true,
  effective_from date NOT NULL,
  effective_to date,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT tax_codes_pkey PRIMARY KEY (id),
  CONSTRAINT tax_codes_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.training_programs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  duration_hours integer,
  trainer_name text,
  training_type text CHECK (training_type = ANY (ARRAY['internal'::text, 'external'::text, 'online'::text])),
  max_participants integer,
  cost_per_participant numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT training_programs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trucks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plate_number text NOT NULL UNIQUE,
  model text,
  year integer,
  capacity_items integer,
  fuel_type text DEFAULT 'diesel'::text CHECK (fuel_type = ANY (ARRAY['diesel'::text, 'petrol'::text, 'electric'::text, 'hybrid'::text])),
  current_driver_id uuid,
  status text DEFAULT 'available'::text CHECK (status = ANY (ARRAY['available'::text, 'in_use'::text, 'maintenance'::text, 'retired'::text])),
  last_maintenance_date date,
  next_maintenance_date date,
  gps_device_id text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  current_odometer numeric DEFAULT 0,
  fuel_efficiency numeric DEFAULT 0,
  maintenance_schedule_km numeric DEFAULT 10000,
  CONSTRAINT trucks_pkey PRIMARY KEY (id),
  CONSTRAINT trucks_current_driver_id_fkey FOREIGN KEY (current_driver_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_notification_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  push_notifications boolean DEFAULT true,
  email_notifications boolean DEFAULT true,
  order_alerts boolean DEFAULT true,
  system_alerts boolean DEFAULT true,
  marketing_emails boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_notification_settings_pkey PRIMARY KEY (id),
  CONSTRAINT user_notification_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text,
  role_id uuid NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  password text,
  name text,
  is_deleted boolean NOT NULL DEFAULT false,
  image_url text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES public.roles(id)
);
CREATE TABLE public.vehicle_expense_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  truck_id uuid NOT NULL,
  expense_id uuid NOT NULL,
  expense_type text NOT NULL CHECK (expense_type = ANY (ARRAY['fuel'::text, 'maintenance'::text, 'insurance'::text, 'registration'::text, 'repair'::text, 'other'::text])),
  amount numeric NOT NULL,
  expense_date date NOT NULL,
  description text,
  odometer_reading numeric,
  quantity numeric,
  unit_price numeric,
  location text,
  vendor_name text,
  receipt_number text,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT vehicle_expense_logs_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_expense_logs_truck_id_fkey FOREIGN KEY (truck_id) REFERENCES public.trucks(id),
  CONSTRAINT vehicle_expense_logs_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES public.expenses(id),
  CONSTRAINT vehicle_expense_logs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.vehicle_maintenance_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  truck_id uuid NOT NULL,
  expense_id uuid,
  maintenance_type text NOT NULL,
  description text NOT NULL,
  cost numeric NOT NULL,
  maintenance_date date NOT NULL,
  odometer_reading numeric,
  next_maintenance_due_date date,
  next_maintenance_odometer numeric,
  vendor_name text,
  receipt_number text,
  status text DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT vehicle_maintenance_logs_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_maintenance_logs_truck_id_fkey FOREIGN KEY (truck_id) REFERENCES public.trucks(id),
  CONSTRAINT vehicle_maintenance_logs_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES public.expenses(id),
  CONSTRAINT vehicle_maintenance_logs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.vendor_bill_po_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_bill_id uuid,
  purchase_order_id uuid,
  amount numeric NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT vendor_bill_po_links_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_bill_po_links_vendor_bill_id_fkey FOREIGN KEY (vendor_bill_id) REFERENCES public.vendor_bills(id),
  CONSTRAINT vendor_bill_po_links_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id)
);
CREATE TABLE public.vendor_bills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL,
  bill_number text NOT NULL,
  bill_date date NOT NULL,
  due_date date NOT NULL,
  total_amount numeric NOT NULL,
  paid_amount numeric DEFAULT 0,
  remaining_amount numeric DEFAULT (total_amount - paid_amount),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'partial'::text, 'paid'::text, 'overdue'::text, 'cancelled'::text])),
  description text,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  purchase_order_id uuid,
  attachment_url text,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  reference_number text,
  updated_by uuid,
  CONSTRAINT vendor_bills_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_bills_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT vendor_bills_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT vendor_bills_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id)
);
CREATE TABLE public.vendor_payment_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL,
  vendor_bill_id uuid,
  purchase_order_id uuid,
  amount numeric NOT NULL,
  payment_date date NOT NULL,
  payment_method text DEFAULT 'cash'::text CHECK (payment_method = ANY (ARRAY['cash'::text, 'bank_transfer'::text, 'cheque'::text, 'upi'::text, 'card'::text, 'other'::text])),
  reference_number text,
  bank_account_id uuid,
  notes text,
  status text DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT vendor_payment_history_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_payment_history_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT vendor_payment_history_vendor_bill_id_fkey FOREIGN KEY (vendor_bill_id) REFERENCES public.vendor_bills(id),
  CONSTRAINT vendor_payment_history_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT vendor_payment_history_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
  CONSTRAINT vendor_payment_history_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.vendor_payment_terms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL,
  payment_terms_days integer DEFAULT 30,
  early_payment_discount_percentage numeric DEFAULT 0,
  early_payment_days integer DEFAULT 0,
  late_payment_penalty_percentage numeric DEFAULT 0,
  credit_limit numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT vendor_payment_terms_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_payment_terms_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT vendor_payment_terms_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.warranty_claims (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid,
  order_id uuid,
  claim_type character varying,
  description text,
  status character varying DEFAULT 'pending'::character varying,
  resolution_notes text,
  warranty_valid_until date,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  resolved_at timestamp without time zone,
  CONSTRAINT warranty_claims_pkey PRIMARY KEY (id),
  CONSTRAINT warranty_claims_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT warranty_claims_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.sales_orders(id)
);
CREATE TABLE public.withdrawal_categories (
  id integer NOT NULL DEFAULT nextval('withdrawal_categories_id_seq'::regclass),
  category_name character varying NOT NULL UNIQUE,
  description text,
  chart_account_code character varying DEFAULT '3200'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT withdrawal_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.withdrawal_subcategories (
  id integer NOT NULL DEFAULT nextval('withdrawal_subcategories_id_seq'::regclass),
  category_id integer,
  subcategory_name character varying NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT withdrawal_subcategories_pkey PRIMARY KEY (id),
  CONSTRAINT withdrawal_subcategories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.withdrawal_categories(id)
);
CREATE TABLE public.withdrawals (
  id integer NOT NULL DEFAULT nextval('withdrawals_id_seq'::regclass),
  partner_id integer,
  category_id integer,
  subcategory_id integer,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  withdrawal_date date NOT NULL DEFAULT CURRENT_DATE,
  description text,
  payment_method character varying NOT NULL DEFAULT 'cash'::character varying,
  bank_account_id uuid,
  reference_number character varying,
  upi_reference character varying,
  notes text,
  journal_entry_id uuid,
  created_by character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT withdrawals_pkey PRIMARY KEY (id),
  CONSTRAINT withdrawals_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT withdrawals_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.withdrawal_categories(id),
  CONSTRAINT withdrawals_subcategory_id_fkey FOREIGN KEY (subcategory_id) REFERENCES public.withdrawal_subcategories(id)
);
CREATE TABLE public.work_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bom_id uuid,
  product_id uuid,
  quantity integer NOT NULL DEFAULT 1,
  status text NOT NULL CHECK (status = ANY (ARRAY['planned'::text, 'in_progress'::text, 'quality_check'::text, 'completed'::text, 'delayed'::text])),
  progress integer NOT NULL DEFAULT 0,
  stage text,
  order_id uuid,
  assigned_to uuid,
  due_date date,
  notes text,
  created_by uuid,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  start_date timestamp without time zone,
  product text,
  updated_at timestamp without time zone DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  updated_by uuid,
  CONSTRAINT work_orders_pkey PRIMARY KEY (id),
  CONSTRAINT work_orders_bom_id_fkey FOREIGN KEY (bom_id) REFERENCES public.boms(id),
  CONSTRAINT work_orders_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT work_orders_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT work_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_work_orders_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_work_orders_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.work_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  day_of_week integer CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone,
  end_time time without time zone,
  is_working_day boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT work_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT work_schedules_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.work_shifts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shift_name character varying NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  break_duration integer DEFAULT 0,
  grace_period_in integer DEFAULT 15,
  grace_period_out integer DEFAULT 15,
  overtime_threshold integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT work_shifts_pkey PRIMARY KEY (id)
);