| trigger_schema | trigger_name                                 | table_name                 | trigger_definition                                                                                                                                                                                                  | trigger_level | trigger_timing | trigger_event_mask | enabled | function_owner         | trigger_function                      |
| -------------- | -------------------------------------------- | -------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------- | -------------- | ------------------ | ------- | ---------------------- | ------------------------------------- |
| public         | audit_chart_of_accounts                      | chart_of_accounts          | CREATE TRIGGER audit_chart_of_accounts AFTER INSERT OR DELETE OR UPDATE ON chart_of_accounts FOR EACH ROW EXECUTE FUNCTION create_audit_trail()                                                                     | ROW           | BEFORE         | MULTI              | e       | postgres               | create_audit_trail                    |
| public         | trg_chart_of_accounts_opening_balance        | chart_of_accounts          | CREATE TRIGGER trg_chart_of_accounts_opening_balance AFTER INSERT OR UPDATE ON chart_of_accounts FOR EACH ROW EXECUTE FUNCTION trigger_create_opening_balance()                                                     | ROW           | BEFORE         | MULTI              | e       | postgres               | trigger_create_opening_balance        |
| public         | trg_chart_of_accounts_timestamp              | chart_of_accounts          | CREATE TRIGGER trg_chart_of_accounts_timestamp BEFORE UPDATE ON chart_of_accounts FOR EACH ROW EXECUTE FUNCTION trigger_update_timestamp()                                                                          | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | trigger_update_timestamp              |
| public         | chat_room_last_message_trigger               | chat_messages              | CREATE TRIGGER chat_room_last_message_trigger AFTER INSERT OR UPDATE ON chat_messages FOR EACH ROW EXECUTE FUNCTION update_chat_room_last_message()                                                                 | ROW           | BEFORE         | MULTI              | e       | postgres               | update_chat_room_last_message         |
| public         | trigger_create_message_notifications         | chat_messages              | CREATE TRIGGER trigger_create_message_notifications AFTER INSERT ON chat_messages FOR EACH ROW EXECUTE FUNCTION create_message_notifications()                                                                      | ROW           | BEFORE         | MULTI              | e       | postgres               | create_message_notifications          |
| public         | chat_participant_count_trigger               | chat_participants          | CREATE TRIGGER chat_participant_count_trigger AFTER INSERT OR DELETE OR UPDATE ON chat_participants FOR EACH ROW EXECUTE FUNCTION update_chat_room_participant_count()                                              | ROW           | BEFORE         | MULTI              | e       | postgres               | update_chat_room_participant_count    |
| public         | trigger_add_creator_as_participant           | chat_rooms                 | CREATE TRIGGER trigger_add_creator_as_participant AFTER INSERT ON chat_rooms FOR EACH ROW EXECUTE FUNCTION add_creator_as_participant()                                                                             | ROW           | BEFORE         | MULTI              | e       | postgres               | add_creator_as_participant            |
| public         | update_chat_rooms_updated_at                 | chat_rooms                 | CREATE TRIGGER update_chat_rooms_updated_at BEFORE UPDATE ON chat_rooms FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()                                                                                    | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | update_updated_at_column              |
| public         | calculate_cost_price_trigger                 | custom_products            | CREATE TRIGGER calculate_cost_price_trigger BEFORE INSERT OR UPDATE ON custom_products FOR EACH ROW EXECUTE FUNCTION calculate_custom_product_cost_price()                                                          | ROW           | BEFORE         | INSERT             | e       | postgres               | calculate_custom_product_cost_price   |
| public         | trg_customers_set_updated_at                 | customers                  | CREATE TRIGGER trg_customers_set_updated_at BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION set_updated_at()                                                                                               | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | set_updated_at                        |
| public         | trg_customers_updated_at                     | customers                  | CREATE TRIGGER trg_customers_updated_at BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()                                                                                         | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | update_updated_at_column              |
| public         | trigger_update_route_efficiency              | deliveries                 | CREATE TRIGGER trigger_update_route_efficiency AFTER INSERT OR DELETE OR UPDATE ON deliveries FOR EACH ROW EXECUTE FUNCTION update_route_efficiency()                                                               | ROW           | BEFORE         | MULTI              | e       | postgres               | update_route_efficiency               |
| public         | trigger_update_delivery_status_from_items    | delivery_items             | CREATE TRIGGER trigger_update_delivery_status_from_items AFTER INSERT OR DELETE OR UPDATE ON delivery_items FOR EACH ROW EXECUTE FUNCTION update_delivery_status_from_items()                                       | ROW           | BEFORE         | MULTI              | e       | postgres               | update_delivery_status_from_items     |
| public         | trigger_update_sales_order_delivery_status   | delivery_items             | CREATE TRIGGER trigger_update_sales_order_delivery_status AFTER UPDATE ON delivery_items FOR EACH ROW WHEN (old.item_status IS DISTINCT FROM new.item_status) EXECUTE FUNCTION update_sales_order_delivery_status() | ROW           | INSTEAD OF     | MULTI              | e       | postgres               | update_sales_order_delivery_status    |
| public         | trg_general_ledger_update_balance            | general_ledger             | CREATE TRIGGER trg_general_ledger_update_balance AFTER INSERT OR DELETE OR UPDATE ON general_ledger FOR EACH ROW EXECUTE FUNCTION trigger_update_account_balance()                                                  | ROW           | BEFORE         | MULTI              | e       | postgres               | trigger_update_account_balance        |
| public         | trg_general_ledger_validate_account          | general_ledger             | CREATE TRIGGER trg_general_ledger_validate_account BEFORE INSERT OR UPDATE ON general_ledger FOR EACH ROW EXECUTE FUNCTION trigger_validate_account_usage()                                                         | ROW           | BEFORE         | INSERT             | e       | postgres               | trigger_validate_account_usage        |
| public         | trigger_update_account_balance               | general_ledger             | CREATE TRIGGER trigger_update_account_balance AFTER INSERT OR DELETE ON general_ledger FOR EACH ROW EXECUTE FUNCTION update_account_balance()                                                                       | ROW           | BEFORE         | MULTI              | e       | postgres               | update_account_balance                |
| public         | audit_journal_entries                        | journal_entries            | CREATE TRIGGER audit_journal_entries AFTER INSERT OR DELETE OR UPDATE ON journal_entries FOR EACH ROW EXECUTE FUNCTION create_audit_trail()                                                                         | ROW           | BEFORE         | MULTI              | e       | postgres               | create_audit_trail                    |
| public         | trg_journal_entries_timestamp                | journal_entries            | CREATE TRIGGER trg_journal_entries_timestamp BEFORE UPDATE ON journal_entries FOR EACH ROW EXECUTE FUNCTION trigger_update_timestamp()                                                                              | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | trigger_update_timestamp              |
| public         | trg_journal_entries_validate_balance         | journal_entries            | CREATE TRIGGER trg_journal_entries_validate_balance BEFORE UPDATE ON journal_entries FOR EACH ROW EXECUTE FUNCTION trigger_validate_journal_balance()                                                               | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | trigger_validate_journal_balance      |
| public         | trigger_create_gl_entries                    | journal_entries            | CREATE TRIGGER trigger_create_gl_entries AFTER UPDATE OF status ON journal_entries FOR EACH ROW EXECUTE FUNCTION create_general_ledger_entries()                                                                    | ROW           | INSTEAD OF     | MULTI              | e       | postgres               | create_general_ledger_entries         |
| public         | update_journal_entries_updated_at            | journal_entries            | CREATE TRIGGER update_journal_entries_updated_at BEFORE UPDATE ON journal_entries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()                                                                          | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | update_updated_at_column              |
| public         | audit_journal_entry_lines                    | journal_entry_lines        | CREATE TRIGGER audit_journal_entry_lines AFTER INSERT OR DELETE OR UPDATE ON journal_entry_lines FOR EACH ROW EXECUTE FUNCTION create_audit_trail()                                                                 | ROW           | BEFORE         | MULTI              | e       | postgres               | create_audit_trail                    |
| public         | trg_journal_lines_update_totals              | journal_entry_lines        | CREATE TRIGGER trg_journal_lines_update_totals AFTER INSERT OR DELETE OR UPDATE ON journal_entry_lines FOR EACH ROW EXECUTE FUNCTION trigger_update_journal_totals()                                                | ROW           | BEFORE         | MULTI              | e       | postgres               | trigger_update_journal_totals         |
| public         | update_journal_entry_lines_updated_at        | journal_entry_lines        | CREATE TRIGGER update_journal_entry_lines_updated_at BEFORE UPDATE ON journal_entry_lines FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()                                                                  | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | update_updated_at_column              |
| public         | trg_payments_audit                           | payments                   | CREATE TRIGGER trg_payments_audit BEFORE INSERT ON payments FOR EACH ROW EXECUTE FUNCTION trigger_audit_financial_transaction()                                                                                     | ROW           | BEFORE         | INSERT             | e       | postgres               | trigger_audit_financial_transaction   |
| public         | trg_payments_update_invoice_status           | payments                   | CREATE TRIGGER trg_payments_update_invoice_status AFTER INSERT OR DELETE OR UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION trigger_update_invoice_payment_status()                                                | ROW           | BEFORE         | MULTI              | e       | postgres               | trigger_update_invoice_payment_status |
| public         | trg_products_set_updated_at                  | products                   | CREATE TRIGGER trg_products_set_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION set_updated_at()                                                                                                 | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | set_updated_at                        |
| public         | trg_products_updated_at                      | products                   | CREATE TRIGGER trg_products_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()                                                                                           | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | update_updated_at_column              |
| public         | update_purchase_order_items_updated_at       | purchase_order_items       | CREATE TRIGGER update_purchase_order_items_updated_at BEFORE UPDATE ON purchase_order_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()                                                                | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | update_updated_at_column              |
| public         | calculate_sales_order_item_tax_trigger       | sales_order_items          | CREATE TRIGGER calculate_sales_order_item_tax_trigger BEFORE INSERT OR UPDATE ON sales_order_items FOR EACH ROW EXECUTE FUNCTION calculate_sales_order_item_tax()                                                   | ROW           | BEFORE         | INSERT             | e       | postgres               | calculate_sales_order_item_tax        |
| public         | update_sales_order_item_totals_delete        | sales_order_items          | CREATE TRIGGER update_sales_order_item_totals_delete AFTER DELETE ON sales_order_items FOR EACH ROW EXECUTE FUNCTION update_sales_order_item_totals()                                                               | ROW           | AFTER          | MULTI              | e       | postgres               | update_sales_order_item_totals        |
| public         | update_sales_order_item_totals_insert        | sales_order_items          | CREATE TRIGGER update_sales_order_item_totals_insert AFTER INSERT ON sales_order_items FOR EACH ROW EXECUTE FUNCTION update_sales_order_item_totals()                                                               | ROW           | BEFORE         | MULTI              | e       | postgres               | update_sales_order_item_totals        |
| public         | update_sales_order_item_totals_update        | sales_order_items          | CREATE TRIGGER update_sales_order_item_totals_update AFTER UPDATE ON sales_order_items FOR EACH ROW EXECUTE FUNCTION update_sales_order_item_totals()                                                               | ROW           | INSTEAD OF     | MULTI              | e       | postgres               | update_sales_order_item_totals        |
| public         | sales_order_analytics_trigger                | sales_orders               | CREATE TRIGGER sales_order_analytics_trigger AFTER INSERT OR DELETE OR UPDATE ON sales_orders FOR EACH ROW EXECUTE FUNCTION trigger_analytics_update()                                                              | ROW           | BEFORE         | MULTI              | e       | postgres               | trigger_analytics_update              |
| public         | trg_sales_orders_set_updated_at              | sales_orders               | CREATE TRIGGER trg_sales_orders_set_updated_at BEFORE UPDATE ON sales_orders FOR EACH ROW EXECUTE FUNCTION set_updated_at()                                                                                         | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | set_updated_at                        |
| public         | trg_sales_orders_updated_at                  | sales_orders               | CREATE TRIGGER trg_sales_orders_updated_at BEFORE UPDATE ON sales_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()                                                                                   | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | update_updated_at_column              |
| public         | apply_stock_adjustment_trigger               | stock_adjustments          | CREATE TRIGGER apply_stock_adjustment_trigger AFTER INSERT ON stock_adjustments FOR EACH ROW EXECUTE FUNCTION apply_stock_adjustment()                                                                              | ROW           | BEFORE         | MULTI              | e       | postgres               | apply_stock_adjustment                |
| public         | stock_adjustments_updated_at_trigger         | stock_adjustments          | CREATE TRIGGER stock_adjustments_updated_at_trigger BEFORE UPDATE ON stock_adjustments FOR EACH ROW EXECUTE FUNCTION update_stock_adjustments_updated_at()                                                          | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | update_stock_adjustments_updated_at   |
| public         | trg_suppliers_set_updated_at                 | suppliers                  | CREATE TRIGGER trg_suppliers_set_updated_at BEFORE UPDATE ON suppliers FOR EACH ROW EXECUTE FUNCTION set_updated_at()                                                                                               | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | set_updated_at                        |
| public         | trg_suppliers_updated_at                     | suppliers                  | CREATE TRIGGER trg_suppliers_updated_at BEFORE UPDATE ON suppliers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()                                                                                         | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | update_updated_at_column              |
| public         | update_support_tickets_updated_at            | support_tickets            | CREATE TRIGGER update_support_tickets_updated_at BEFORE UPDATE ON support_tickets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()                                                                          | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | update_updated_at_column              |
| public         | update_user_notification_settings_updated_at | user_notification_settings | CREATE TRIGGER update_user_notification_settings_updated_at BEFORE UPDATE ON user_notification_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()                                                    | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | update_updated_at_column              |
| public         | trg_vendor_payments_audit                    | vendor_payment_history     | CREATE TRIGGER trg_vendor_payments_audit BEFORE INSERT ON vendor_payment_history FOR EACH ROW EXECUTE FUNCTION trigger_audit_financial_transaction()                                                                | ROW           | BEFORE         | INSERT             | e       | postgres               | trigger_audit_financial_transaction   |
| public         | trg_vendor_payments_update_po_status         | vendor_payment_history     | CREATE TRIGGER trg_vendor_payments_update_po_status AFTER INSERT OR DELETE OR UPDATE ON vendor_payment_history FOR EACH ROW EXECUTE FUNCTION trigger_update_po_payment_status()                                     | ROW           | BEFORE         | MULTI              | e       | postgres               | trigger_update_po_payment_status      |
| public         | trigger_update_po_payment_status             | vendor_payment_history     | CREATE TRIGGER trigger_update_po_payment_status AFTER INSERT OR DELETE OR UPDATE ON vendor_payment_history FOR EACH ROW EXECUTE FUNCTION update_purchase_order_payment_status()                                     | ROW           | BEFORE         | MULTI              | e       | postgres               | update_purchase_order_payment_status  |
| public         | trigger_update_vendor_bill_status            | vendor_payment_history     | CREATE TRIGGER trigger_update_vendor_bill_status AFTER INSERT OR DELETE OR UPDATE ON vendor_payment_history FOR EACH ROW EXECUTE FUNCTION update_vendor_bill_status()                                               | ROW           | BEFORE         | MULTI              | e       | postgres               | update_vendor_bill_status             |
| public         | trg_work_orders_set_updated_at               | work_orders                | CREATE TRIGGER trg_work_orders_set_updated_at BEFORE UPDATE ON work_orders FOR EACH ROW EXECUTE FUNCTION set_updated_at()                                                                                           | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | set_updated_at                        |
| public         | trg_work_orders_updated_at                   | work_orders                | CREATE TRIGGER trg_work_orders_updated_at BEFORE UPDATE ON work_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()                                                                                     | ROW           | INSTEAD OF     | INSERT             | e       | postgres               | update_updated_at_column              |
| realtime       | tr_check_filters                             | subscription               | CREATE TRIGGER tr_check_filters BEFORE INSERT OR UPDATE ON realtime.subscription FOR EACH ROW EXECUTE FUNCTION realtime.subscription_check_filters()                                                                | ROW           | BEFORE         | INSERT             | e       | supabase_admin         | subscription_check_filters            |
| storage        | enforce_bucket_name_length_trigger           | buckets                    | CREATE TRIGGER enforce_bucket_name_length_trigger BEFORE INSERT OR UPDATE OF name ON storage.buckets FOR EACH ROW EXECUTE FUNCTION storage.enforce_bucket_name_length()                                             | ROW           | BEFORE         | INSERT             | e       | supabase_storage_admin | enforce_bucket_name_length            |
| storage        | objects_delete_delete_prefix                 | objects                    | CREATE TRIGGER objects_delete_delete_prefix AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger()                                                                 | ROW           | AFTER          | MULTI              | e       | supabase_storage_admin | delete_prefix_hierarchy_trigger       |
| storage        | objects_insert_create_prefix                 | objects                    | CREATE TRIGGER objects_insert_create_prefix BEFORE INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.objects_insert_prefix_trigger()                                                                  | ROW           | BEFORE         | INSERT             | e       | supabase_storage_admin | objects_insert_prefix_trigger         |
| storage        | objects_update_create_prefix                 | objects                    | CREATE TRIGGER objects_update_create_prefix BEFORE UPDATE ON storage.objects FOR EACH ROW WHEN (new.name <> old.name OR new.bucket_id <> old.bucket_id) EXECUTE FUNCTION storage.objects_update_prefix_trigger()    | ROW           | INSTEAD OF     | INSERT             | e       | supabase_storage_admin | objects_update_prefix_trigger         |
| storage        | update_objects_updated_at                    | objects                    | CREATE TRIGGER update_objects_updated_at BEFORE UPDATE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.update_updated_at_column()                                                                          | ROW           | INSTEAD OF     | INSERT             | e       | supabase_storage_admin | update_updated_at_column              |
| storage        | prefixes_create_hierarchy                    | prefixes                   | CREATE TRIGGER prefixes_create_hierarchy BEFORE INSERT ON storage.prefixes FOR EACH ROW WHEN (pg_trigger_depth() < 1) EXECUTE FUNCTION storage.prefixes_insert_trigger()                                            | ROW           | BEFORE         | INSERT             | e       | supabase_storage_admin | prefixes_insert_trigger               |
| storage        | prefixes_delete_hierarchy                    | prefixes                   | CREATE TRIGGER prefixes_delete_hierarchy AFTER DELETE ON storage.prefixes FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger()                                                                   | ROW           | AFTER          | MULTI              | e       | supabase_storage_admin | delete_prefix_hierarchy_trigger       |