[
  {
    "trigger_schema": "public",
    "table_name": "chart_of_accounts",
    "trigger_name": "audit_chart_of_accounts",
    "trigger_definition": "CREATE TRIGGER audit_chart_of_accounts AFTER INSERT OR DELETE OR UPDATE ON chart_of_accounts FOR EACH ROW EXECUTE FUNCTION create_audit_trail()",
    "enabled_flag": "O",
    "function_oid": 81946,
    "function_name": "create_audit_trail",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.create_audit_trail()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n  audit_action audit_action;\r\n  old_data JSONB;\r\n  new_data JSONB;\r\nBEGIN\r\n  -- Determine action\r\n  IF TG_OP = 'DELETE' THEN\r\n    audit_action := 'DELETE';\r\n    old_data := row_to_json(OLD)::JSONB;\r\n    new_data := NULL;\r\n  ELSIF TG_OP = 'UPDATE' THEN\r\n    audit_action := 'UPDATE';\r\n    old_data := row_to_json(OLD)::JSONB;\r\n    new_data := row_to_json(NEW)::JSONB;\r\n  ELSIF TG_OP = 'INSERT' THEN\r\n    audit_action := 'CREATE';\r\n    old_data := NULL;\r\n    new_data := row_to_json(NEW)::JSONB;\r\n  END IF;\r\n\r\n  -- Insert audit record\r\n  INSERT INTO audit_trail (\r\n    table_name,\r\n    record_id,\r\n    action,\r\n    old_values,\r\n    new_values,\r\n    user_id,\r\n    timestamp\r\n  ) VALUES (\r\n    TG_TABLE_NAME,\r\n    COALESCE(NEW.id, OLD.id),\r\n    audit_action,\r\n    old_data,\r\n    new_data,\r\n    COALESCE(NEW.created_by, NEW.updated_by, OLD.created_by, OLD.updated_by),\r\n    NOW()\r\n  );\r\n\r\n  RETURN COALESCE(NEW, OLD);\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "chart_of_accounts",
    "trigger_name": "trg_chart_of_accounts_opening_balance",
    "trigger_definition": "CREATE TRIGGER trg_chart_of_accounts_opening_balance AFTER INSERT OR UPDATE ON chart_of_accounts FOR EACH ROW EXECUTE FUNCTION trigger_create_opening_balance()",
    "enabled_flag": "O",
    "function_oid": 131996,
    "function_name": "trigger_create_opening_balance",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_create_opening_balance()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    -- Create opening balance entry if opening_balance is set\r\n    IF NEW.opening_balance IS NOT NULL AND NEW.opening_balance != 0 THEN\r\n        INSERT INTO opening_balances (\r\n            account_id,\r\n            opening_date,\r\n            debit_amount,\r\n            credit_amount\r\n        ) VALUES (\r\n            NEW.id,\r\n            CURRENT_DATE,\r\n            CASE WHEN NEW.normal_balance = 'DEBIT' AND NEW.opening_balance > 0 THEN NEW.opening_balance ELSE 0 END,\r\n            CASE WHEN NEW.normal_balance = 'CREDIT' AND NEW.opening_balance > 0 THEN NEW.opening_balance ELSE 0 END\r\n        )\r\n        ON CONFLICT (account_id) DO UPDATE SET\r\n            debit_amount = CASE WHEN NEW.normal_balance = 'DEBIT' AND NEW.opening_balance > 0 THEN NEW.opening_balance ELSE 0 END,\r\n            credit_amount = CASE WHEN NEW.normal_balance = 'CREDIT' AND NEW.opening_balance > 0 THEN NEW.opening_balance ELSE 0 END;\r\n    END IF;\r\n    \r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "chart_of_accounts",
    "trigger_name": "trg_chart_of_accounts_timestamp",
    "trigger_definition": "CREATE TRIGGER trg_chart_of_accounts_timestamp BEFORE UPDATE ON chart_of_accounts FOR EACH ROW EXECUTE FUNCTION trigger_update_timestamp()",
    "enabled_flag": "O",
    "function_oid": 131998,
    "function_name": "trigger_update_timestamp",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_update_timestamp()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    NEW.updated_at = CURRENT_TIMESTAMP;\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "chat_messages",
    "trigger_name": "chat_room_last_message_trigger",
    "trigger_definition": "CREATE TRIGGER chat_room_last_message_trigger AFTER INSERT OR UPDATE ON chat_messages FOR EACH ROW EXECUTE FUNCTION update_chat_room_last_message()",
    "enabled_flag": "O",
    "function_oid": 117517,
    "function_name": "update_chat_room_last_message",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_chat_room_last_message()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    IF TG_OP = 'INSERT' THEN\r\n        UPDATE chat_rooms \r\n        SET last_message_at = NEW.sent_at\r\n        WHERE id = NEW.room_id;\r\n        RETURN NEW;\r\n    ELSIF TG_OP = 'UPDATE' THEN\r\n        UPDATE chat_rooms \r\n        SET last_message_at = NEW.sent_at\r\n        WHERE id = NEW.room_id;\r\n        RETURN NEW;\r\n    END IF;\r\n    RETURN NULL;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "chat_messages",
    "trigger_name": "trigger_create_message_notifications",
    "trigger_definition": "CREATE TRIGGER trigger_create_message_notifications AFTER INSERT ON chat_messages FOR EACH ROW EXECUTE FUNCTION create_message_notifications()",
    "enabled_flag": "O",
    "function_oid": 117571,
    "function_name": "create_message_notifications",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.create_message_notifications()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    -- Create notifications for all participants except the sender\r\n    INSERT INTO chat_notifications (user_id, room_id, message_id, type)\r\n    SELECT \r\n        cp.user_id,\r\n        NEW.room_id,\r\n        NEW.id,\r\n        'message'\r\n    FROM chat_participants cp\r\n    WHERE cp.room_id = NEW.room_id \r\n    AND cp.user_id != NEW.sender_id\r\n    AND cp.is_active = true;\r\n    \r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "chat_participants",
    "trigger_name": "chat_participant_count_trigger",
    "trigger_definition": "CREATE TRIGGER chat_participant_count_trigger AFTER INSERT OR DELETE OR UPDATE ON chat_participants FOR EACH ROW EXECUTE FUNCTION update_chat_room_participant_count()",
    "enabled_flag": "O",
    "function_oid": 117515,
    "function_name": "update_chat_room_participant_count",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_chat_room_participant_count()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    IF TG_OP = 'INSERT' THEN\r\n        UPDATE chat_rooms \r\n        SET participant_count = (\r\n            SELECT COUNT(*) \r\n            FROM chat_participants \r\n            WHERE room_id = NEW.room_id AND is_active = true\r\n        )\r\n        WHERE id = NEW.room_id;\r\n        RETURN NEW;\r\n    ELSIF TG_OP = 'UPDATE' THEN\r\n        UPDATE chat_rooms \r\n        SET participant_count = (\r\n            SELECT COUNT(*) \r\n            FROM chat_participants \r\n            WHERE room_id = NEW.room_id AND is_active = true\r\n        )\r\n        WHERE id = NEW.room_id;\r\n        RETURN NEW;\r\n    ELSIF TG_OP = 'DELETE' THEN\r\n        UPDATE chat_rooms \r\n        SET participant_count = (\r\n            SELECT COUNT(*) \r\n            FROM chat_participants \r\n            WHERE room_id = OLD.room_id AND is_active = true\r\n        )\r\n        WHERE id = OLD.room_id;\r\n        RETURN OLD;\r\n    END IF;\r\n    RETURN NULL;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "chat_rooms",
    "trigger_name": "trigger_add_creator_as_participant",
    "trigger_definition": "CREATE TRIGGER trigger_add_creator_as_participant AFTER INSERT ON chat_rooms FOR EACH ROW EXECUTE FUNCTION add_creator_as_participant()",
    "enabled_flag": "O",
    "function_oid": 117569,
    "function_name": "add_creator_as_participant",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.add_creator_as_participant()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    INSERT INTO chat_participants (room_id, user_id, role)\r\n    VALUES (NEW.id, NEW.created_by, 'admin')\r\n    ON CONFLICT (room_id, user_id) DO NOTHING;\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "chat_rooms",
    "trigger_name": "update_chat_rooms_updated_at",
    "trigger_definition": "CREATE TRIGGER update_chat_rooms_updated_at BEFORE UPDATE ON chat_rooms FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()",
    "enabled_flag": "O",
    "function_oid": 36022,
    "function_name": "update_updated_at_column",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_updated_at_column()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    NEW.updated_at = NOW();\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "custom_products",
    "trigger_name": "calculate_cost_price_trigger",
    "trigger_definition": "CREATE TRIGGER calculate_cost_price_trigger BEFORE INSERT OR UPDATE ON custom_products FOR EACH ROW EXECUTE FUNCTION calculate_custom_product_cost_price()",
    "enabled_flag": "O",
    "function_oid": 123992,
    "function_name": "calculate_custom_product_cost_price",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.calculate_custom_product_cost_price()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    -- If cost_price is null but price (MRP) is set, calculate cost_price\r\n    -- Using a default margin of 30% (cost = 70% of MRP)\r\n    IF NEW.cost_price IS NULL AND NEW.price IS NOT NULL AND NEW.price > 0 THEN\r\n        NEW.cost_price := ROUND(NEW.price * 0.70, 2);  -- 30% margin\r\n    END IF;\r\n    \r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "customers",
    "trigger_name": "trg_customers_set_updated_at",
    "trigger_definition": "CREATE TRIGGER trg_customers_set_updated_at BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION set_updated_at()",
    "enabled_flag": "O",
    "function_oid": 36192,
    "function_name": "set_updated_at",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.set_updated_at()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n  NEW.updated_at = now();\r\n  RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "customers",
    "trigger_name": "trg_customers_updated_at",
    "trigger_definition": "CREATE TRIGGER trg_customers_updated_at BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()",
    "enabled_flag": "O",
    "function_oid": 36022,
    "function_name": "update_updated_at_column",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_updated_at_column()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    NEW.updated_at = NOW();\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "deliveries",
    "trigger_name": "trigger_update_route_efficiency",
    "trigger_definition": "CREATE TRIGGER trigger_update_route_efficiency AFTER INSERT OR DELETE OR UPDATE ON deliveries FOR EACH ROW EXECUTE FUNCTION update_route_efficiency()",
    "enabled_flag": "O",
    "function_oid": 87298,
    "function_name": "update_route_efficiency",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_route_efficiency()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    -- Update route statistics and efficiency\r\n    UPDATE delivery_routes \r\n    SET \r\n        route_efficiency_score = (\r\n            SELECT \r\n                CASE \r\n                    WHEN total_deliveries = 0 THEN 0\r\n                    ELSE ROUND(\r\n                        (completed_deliveries::numeric / total_deliveries::numeric) * 100 * \r\n                        (1 - (COALESCE(route_distance, 0) / NULLIF(COALESCE(route_distance, 0) + 100, 0))), 2\r\n                    )\r\n                END\r\n        ),\r\n        current_load_items = (\r\n            SELECT COALESCE(SUM(di.quantity_to_deliver), 0)\r\n            FROM deliveries d\r\n            JOIN delivery_items di ON d.id = di.delivery_id\r\n            WHERE d.route_id = COALESCE(NEW.route_id, OLD.route_id) \r\n            AND di.item_status IN ('loaded', 'in_transit')\r\n        ),\r\n        updated_at = now()\r\n    WHERE id = COALESCE(NEW.route_id, OLD.route_id);\r\n    \r\n    RETURN COALESCE(NEW, OLD);\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "delivery_items",
    "trigger_name": "trigger_update_delivery_status_from_items",
    "trigger_definition": "CREATE TRIGGER trigger_update_delivery_status_from_items AFTER INSERT OR DELETE OR UPDATE ON delivery_items FOR EACH ROW EXECUTE FUNCTION update_delivery_status_from_items()",
    "enabled_flag": "O",
    "function_oid": 86941,
    "function_name": "update_delivery_status_from_items",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_delivery_status_from_items()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n  -- Update delivery status based on item statuses\r\n  -- Implementation depends on business logic\r\n  RETURN COALESCE(NEW, OLD);\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "delivery_items",
    "trigger_name": "trigger_update_sales_order_delivery_status",
    "trigger_definition": "CREATE TRIGGER trigger_update_sales_order_delivery_status AFTER UPDATE ON delivery_items FOR EACH ROW WHEN (old.item_status IS DISTINCT FROM new.item_status) EXECUTE FUNCTION update_sales_order_delivery_status()",
    "enabled_flag": "O",
    "function_oid": 99300,
    "function_name": "update_sales_order_delivery_status",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_sales_order_delivery_status()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n  -- Update sales order delivery status based on delivery items\r\n  -- Implementation depends on business logic\r\n  RETURN COALESCE(NEW, OLD);\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "general_ledger",
    "trigger_name": "trg_general_ledger_update_balance",
    "trigger_definition": "CREATE TRIGGER trg_general_ledger_update_balance AFTER INSERT OR DELETE OR UPDATE ON general_ledger FOR EACH ROW EXECUTE FUNCTION trigger_update_account_balance()",
    "enabled_flag": "O",
    "function_oid": 131990,
    "function_name": "trigger_update_account_balance",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_update_account_balance()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n    affected_account_id UUID;\r\nBEGIN\r\n    -- Handle different trigger events\r\n    IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN\r\n        affected_account_id := NEW.account_id;\r\n        RETURN NEW;\r\n    ELSIF TG_OP = 'DELETE' THEN\r\n        affected_account_id := OLD.account_id;\r\n        RETURN OLD;\r\n    END IF;\r\n    \r\n    -- Update account balance\r\n    UPDATE chart_of_accounts \r\n    SET \r\n        current_balance = calculate_account_balance(affected_account_id),\r\n        updated_at = CURRENT_TIMESTAMP\r\n    WHERE id = affected_account_id;\r\n    \r\n    RETURN COALESCE(NEW, OLD);\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "general_ledger",
    "trigger_name": "trg_general_ledger_validate_account",
    "trigger_definition": "CREATE TRIGGER trg_general_ledger_validate_account BEFORE INSERT OR UPDATE ON general_ledger FOR EACH ROW EXECUTE FUNCTION trigger_validate_account_usage()",
    "enabled_flag": "O",
    "function_oid": 132001,
    "function_name": "trigger_validate_account_usage",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_validate_account_usage()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n    account_info RECORD;\r\nBEGIN\r\n    -- Get account information\r\n    SELECT account_type, is_active INTO account_info\r\n    FROM chart_of_accounts\r\n    WHERE id = NEW.account_id;\r\n    \r\n    -- Validate account is active\r\n    IF NOT account_info.is_active THEN\r\n        RAISE EXCEPTION 'Cannot post to inactive account';\r\n    END IF;\r\n    \r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "general_ledger",
    "trigger_name": "trigger_update_account_balance",
    "trigger_definition": "CREATE TRIGGER trigger_update_account_balance AFTER INSERT OR DELETE ON general_ledger FOR EACH ROW EXECUTE FUNCTION update_account_balance()",
    "enabled_flag": "O",
    "function_oid": 81942,
    "function_name": "update_account_balance",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_account_balance()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n  IF TG_OP = 'INSERT' THEN\r\n    UPDATE chart_of_accounts \r\n    SET current_balance = CASE \r\n      WHEN normal_balance = 'DEBIT' \r\n      THEN current_balance + NEW.debit_amount - NEW.credit_amount\r\n      ELSE current_balance + NEW.credit_amount - NEW.debit_amount\r\n    END,\r\n    updated_at = NOW()\r\n    WHERE id = NEW.account_id;\r\n    \r\n    RETURN NEW;\r\n  ELSIF TG_OP = 'DELETE' THEN\r\n    UPDATE chart_of_accounts \r\n    SET current_balance = CASE \r\n      WHEN normal_balance = 'DEBIT' \r\n      THEN current_balance - OLD.debit_amount + OLD.credit_amount\r\n      ELSE current_balance - OLD.credit_amount + OLD.debit_amount\r\n    END,\r\n    updated_at = NOW()\r\n    WHERE id = OLD.account_id;\r\n    \r\n    RETURN OLD;\r\n  END IF;\r\n  \r\n  RETURN NULL;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "invoices",
    "trigger_name": "trg_invoices_create_journal",
    "trigger_definition": "CREATE TRIGGER trg_invoices_create_journal AFTER INSERT ON invoices FOR EACH ROW EXECUTE FUNCTION trigger_create_sales_journal_entry()",
    "enabled_flag": "O",
    "function_oid": 132138,
    "function_name": "trigger_create_sales_journal_entry",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_create_sales_journal_entry()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n    ar_account_id UUID;\r\n    sales_account_id UUID;\r\n    journal_id UUID;\r\n    customer_name TEXT;\r\n    amount_to_record DECIMAL;\r\nBEGIN\r\n    -- Determine amount to record with better logic\r\n    amount_to_record := COALESCE(NEW.final_price, NEW.total, NEW.total_price, NEW.grand_total, 0);\r\n    \r\n    -- Skip if total is null or zero\r\n    IF amount_to_record IS NULL OR amount_to_record = 0 THEN\r\n        RETURN NEW;\r\n    END IF;\r\n    \r\n    -- Get account IDs with flexible lookup\r\n    SELECT id INTO ar_account_id FROM chart_of_accounts WHERE account_code IN ('1200', '1100') ORDER BY account_code LIMIT 1;\r\n    SELECT id INTO sales_account_id FROM chart_of_accounts WHERE account_code IN ('4010', '4000', '4001') ORDER BY account_code LIMIT 1;\r\n    \r\n    -- Skip if accounts not found but log warning\r\n    IF ar_account_id IS NULL OR sales_account_id IS NULL THEN\r\n        RAISE WARNING 'Required accounts not found for sales journal entry: AR=%, Sales=%. Available codes: %', \r\n            ar_account_id, sales_account_id,\r\n            (SELECT array_agg(account_code) FROM chart_of_accounts WHERE account_code IN ('1200','1100','4010','4000','4001'));\r\n        RETURN NEW;\r\n    END IF;\r\n    \r\n    -- Get customer name\r\n    customer_name := COALESCE(NEW.customer_name, 'Customer');\r\n    \r\n    -- Create journal entry for sale\r\n    journal_id := create_journal_entry(\r\n        CURRENT_DATE,\r\n        'Sale to ' || customer_name,\r\n        CASE \r\n            WHEN TG_TABLE_NAME = 'sales_orders' THEN 'SO-' || NEW.id::text\r\n            WHEN TG_TABLE_NAME = 'invoices' THEN 'INV-' || NEW.id::text\r\n            ELSE 'SALE-' || NEW.id::text\r\n        END\r\n    );\r\n    \r\n    -- Debit Accounts Receivable (increase asset)\r\n    PERFORM add_journal_entry_line(journal_id, ar_account_id, amount_to_record, 0, 'Invoice created');\r\n    \r\n    -- Credit Sales Revenue (increase revenue)\r\n    PERFORM add_journal_entry_line(journal_id, sales_account_id, 0, amount_to_record, 'Sales revenue');\r\n    \r\n    -- Post the journal entry\r\n    PERFORM post_journal_entry(journal_id);\r\n    \r\n    RETURN NEW;\r\nEXCEPTION\r\n    WHEN OTHERS THEN\r\n        -- Log error and continue without failing the sale\r\n        RAISE WARNING 'Failed to create journal entry for sale %: %', NEW.id, SQLERRM;\r\n        RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "journal_entries",
    "trigger_name": "audit_journal_entries",
    "trigger_definition": "CREATE TRIGGER audit_journal_entries AFTER INSERT OR DELETE OR UPDATE ON journal_entries FOR EACH ROW EXECUTE FUNCTION create_audit_trail()",
    "enabled_flag": "O",
    "function_oid": 81946,
    "function_name": "create_audit_trail",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.create_audit_trail()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n  audit_action audit_action;\r\n  old_data JSONB;\r\n  new_data JSONB;\r\nBEGIN\r\n  -- Determine action\r\n  IF TG_OP = 'DELETE' THEN\r\n    audit_action := 'DELETE';\r\n    old_data := row_to_json(OLD)::JSONB;\r\n    new_data := NULL;\r\n  ELSIF TG_OP = 'UPDATE' THEN\r\n    audit_action := 'UPDATE';\r\n    old_data := row_to_json(OLD)::JSONB;\r\n    new_data := row_to_json(NEW)::JSONB;\r\n  ELSIF TG_OP = 'INSERT' THEN\r\n    audit_action := 'CREATE';\r\n    old_data := NULL;\r\n    new_data := row_to_json(NEW)::JSONB;\r\n  END IF;\r\n\r\n  -- Insert audit record\r\n  INSERT INTO audit_trail (\r\n    table_name,\r\n    record_id,\r\n    action,\r\n    old_values,\r\n    new_values,\r\n    user_id,\r\n    timestamp\r\n  ) VALUES (\r\n    TG_TABLE_NAME,\r\n    COALESCE(NEW.id, OLD.id),\r\n    audit_action,\r\n    old_data,\r\n    new_data,\r\n    COALESCE(NEW.created_by, NEW.updated_by, OLD.created_by, OLD.updated_by),\r\n    NOW()\r\n  );\r\n\r\n  RETURN COALESCE(NEW, OLD);\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "journal_entries",
    "trigger_name": "trg_journal_entries_timestamp",
    "trigger_definition": "CREATE TRIGGER trg_journal_entries_timestamp BEFORE UPDATE ON journal_entries FOR EACH ROW EXECUTE FUNCTION trigger_update_timestamp()",
    "enabled_flag": "O",
    "function_oid": 131998,
    "function_name": "trigger_update_timestamp",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_update_timestamp()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    NEW.updated_at = CURRENT_TIMESTAMP;\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "journal_entries",
    "trigger_name": "trg_journal_entries_validate_balance",
    "trigger_definition": "CREATE TRIGGER trg_journal_entries_validate_balance BEFORE UPDATE ON journal_entries FOR EACH ROW EXECUTE FUNCTION trigger_validate_journal_balance()",
    "enabled_flag": "O",
    "function_oid": 131994,
    "function_name": "trigger_validate_journal_balance",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_validate_journal_balance()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    -- Only validate when status changes to POSTED\r\n    IF NEW.status = 'POSTED' AND OLD.status != 'POSTED' THEN\r\n        IF ABS(COALESCE(NEW.total_debit, 0) - COALESCE(NEW.total_credit, 0)) > 0.01 THEN\r\n            RAISE EXCEPTION 'Cannot post unbalanced journal entry. Debits: %, Credits: %', \r\n                NEW.total_debit, NEW.total_credit;\r\n        END IF;\r\n    END IF;\r\n    \r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "journal_entries",
    "trigger_name": "trigger_create_gl_entries",
    "trigger_definition": "CREATE TRIGGER trigger_create_gl_entries AFTER UPDATE OF status ON journal_entries FOR EACH ROW EXECUTE FUNCTION create_general_ledger_entries()",
    "enabled_flag": "O",
    "function_oid": 81944,
    "function_name": "create_general_ledger_entries",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.create_general_ledger_entries()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n  line_rec RECORD;\r\n  running_balance NUMERIC(15,2);\r\nBEGIN\r\n  -- Only process when status changes to 'POSTED'\r\n  IF NEW.status = 'POSTED' AND (OLD.status IS NULL OR OLD.status != 'POSTED') THEN\r\n    \r\n    -- Process each journal entry line\r\n    FOR line_rec IN \r\n      SELECT * FROM journal_entry_lines \r\n      WHERE journal_entry_id = NEW.id \r\n      ORDER BY line_number\r\n    LOOP\r\n      -- Calculate running balance for the account\r\n      SELECT COALESCE(\r\n        (SELECT running_balance FROM general_ledger \r\n         WHERE account_id = line_rec.account_id \r\n         ORDER BY created_at DESC, id DESC \r\n         LIMIT 1), \r\n        (SELECT opening_balance FROM chart_of_accounts WHERE id = line_rec.account_id)\r\n      ) INTO running_balance;\r\n      \r\n      -- Update running balance\r\n      running_balance := running_balance + line_rec.debit_amount - line_rec.credit_amount;\r\n      \r\n      -- Insert into general ledger\r\n      INSERT INTO general_ledger (\r\n        account_id,\r\n        journal_entry_id,\r\n        journal_line_id,\r\n        transaction_date,\r\n        posting_date,\r\n        description,\r\n        reference,\r\n        debit_amount,\r\n        credit_amount,\r\n        running_balance,\r\n        source_document_type,\r\n        source_document_id\r\n      ) VALUES (\r\n        line_rec.account_id,\r\n        NEW.id,\r\n        line_rec.id,\r\n        NEW.entry_date,\r\n        NEW.posting_date,\r\n        line_rec.description,\r\n        NEW.reference_number,\r\n        line_rec.debit_amount,\r\n        line_rec.credit_amount,\r\n        running_balance,\r\n        NEW.source_document_type,\r\n        NEW.source_document_id\r\n      );\r\n    END LOOP;\r\n    \r\n    -- Update posting timestamp\r\n    UPDATE journal_entries \r\n    SET posted_at = NOW() \r\n    WHERE id = NEW.id;\r\n  END IF;\r\n  \r\n  RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "journal_entries",
    "trigger_name": "update_journal_entries_updated_at",
    "trigger_definition": "CREATE TRIGGER update_journal_entries_updated_at BEFORE UPDATE ON journal_entries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()",
    "enabled_flag": "O",
    "function_oid": 36022,
    "function_name": "update_updated_at_column",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_updated_at_column()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    NEW.updated_at = NOW();\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "journal_entry_lines",
    "trigger_name": "audit_journal_entry_lines",
    "trigger_definition": "CREATE TRIGGER audit_journal_entry_lines AFTER INSERT OR DELETE OR UPDATE ON journal_entry_lines FOR EACH ROW EXECUTE FUNCTION create_audit_trail()",
    "enabled_flag": "O",
    "function_oid": 81946,
    "function_name": "create_audit_trail",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.create_audit_trail()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n  audit_action audit_action;\r\n  old_data JSONB;\r\n  new_data JSONB;\r\nBEGIN\r\n  -- Determine action\r\n  IF TG_OP = 'DELETE' THEN\r\n    audit_action := 'DELETE';\r\n    old_data := row_to_json(OLD)::JSONB;\r\n    new_data := NULL;\r\n  ELSIF TG_OP = 'UPDATE' THEN\r\n    audit_action := 'UPDATE';\r\n    old_data := row_to_json(OLD)::JSONB;\r\n    new_data := row_to_json(NEW)::JSONB;\r\n  ELSIF TG_OP = 'INSERT' THEN\r\n    audit_action := 'CREATE';\r\n    old_data := NULL;\r\n    new_data := row_to_json(NEW)::JSONB;\r\n  END IF;\r\n\r\n  -- Insert audit record\r\n  INSERT INTO audit_trail (\r\n    table_name,\r\n    record_id,\r\n    action,\r\n    old_values,\r\n    new_values,\r\n    user_id,\r\n    timestamp\r\n  ) VALUES (\r\n    TG_TABLE_NAME,\r\n    COALESCE(NEW.id, OLD.id),\r\n    audit_action,\r\n    old_data,\r\n    new_data,\r\n    COALESCE(NEW.created_by, NEW.updated_by, OLD.created_by, OLD.updated_by),\r\n    NOW()\r\n  );\r\n\r\n  RETURN COALESCE(NEW, OLD);\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "journal_entry_lines",
    "trigger_name": "trg_journal_lines_update_totals",
    "trigger_definition": "CREATE TRIGGER trg_journal_lines_update_totals AFTER INSERT OR DELETE OR UPDATE ON journal_entry_lines FOR EACH ROW EXECUTE FUNCTION trigger_update_journal_totals()",
    "enabled_flag": "O",
    "function_oid": 131992,
    "function_name": "trigger_update_journal_totals",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_update_journal_totals()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n    je_id UUID;\r\nBEGIN\r\n    -- Get journal entry ID\r\n    IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN\r\n        je_id := NEW.journal_entry_id;\r\n    ELSIF TG_OP = 'DELETE' THEN\r\n        je_id := OLD.journal_entry_id;\r\n    END IF;\r\n    \r\n    -- Update journal entry totals\r\n    UPDATE journal_entries \r\n    SET \r\n        total_debit = (\r\n            SELECT COALESCE(SUM(debit_amount), 0)\r\n            FROM journal_entry_lines \r\n            WHERE journal_entry_id = je_id\r\n        ),\r\n        total_credit = (\r\n            SELECT COALESCE(SUM(credit_amount), 0)\r\n            FROM journal_entry_lines \r\n            WHERE journal_entry_id = je_id\r\n        ),\r\n        updated_at = CURRENT_TIMESTAMP\r\n    WHERE id = je_id;\r\n    \r\n    RETURN COALESCE(NEW, OLD);\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "journal_entry_lines",
    "trigger_name": "update_journal_entry_lines_updated_at",
    "trigger_definition": "CREATE TRIGGER update_journal_entry_lines_updated_at BEFORE UPDATE ON journal_entry_lines FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()",
    "enabled_flag": "O",
    "function_oid": 36022,
    "function_name": "update_updated_at_column",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_updated_at_column()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    NEW.updated_at = NOW();\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "payments",
    "trigger_name": "trg_payments_audit",
    "trigger_definition": "CREATE TRIGGER trg_payments_audit BEFORE INSERT ON payments FOR EACH ROW EXECUTE FUNCTION trigger_audit_financial_transaction()",
    "enabled_flag": "O",
    "function_oid": 132003,
    "function_name": "trigger_audit_financial_transaction",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_audit_financial_transaction()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    -- This can be extended to log to an audit table\r\n    -- For now, just ensure created_at is set\r\n    IF TG_OP = 'INSERT' THEN\r\n        IF NEW.created_at IS NULL THEN\r\n            NEW.created_at = CURRENT_TIMESTAMP;\r\n        END IF;\r\n        RETURN NEW;\r\n    END IF;\r\n    \r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "payments",
    "trigger_name": "trg_payments_create_journal",
    "trigger_definition": "CREATE TRIGGER trg_payments_create_journal AFTER INSERT ON payments FOR EACH ROW EXECUTE FUNCTION trigger_create_payment_journal_entry()",
    "enabled_flag": "O",
    "function_oid": 132137,
    "function_name": "trigger_create_payment_journal_entry",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_create_payment_journal_entry()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n    cash_account_id UUID;\r\n    ar_account_id UUID;\r\n    journal_id UUID;\r\n    customer_name TEXT;\r\nBEGIN\r\n    -- Skip if amount is null or zero\r\n    IF NEW.amount IS NULL OR NEW.amount = 0 THEN\r\n        RETURN NEW;\r\n    END IF;\r\n    \r\n    -- Get account IDs with flexible lookup (try multiple account codes)\r\n    SELECT id INTO cash_account_id FROM chart_of_accounts WHERE account_code IN ('1001', '1010') ORDER BY account_code LIMIT 1;\r\n    SELECT id INTO ar_account_id FROM chart_of_accounts WHERE account_code IN ('1200', '1100') ORDER BY account_code LIMIT 1;\r\n    \r\n    -- Skip if accounts not found but log warning\r\n    IF cash_account_id IS NULL OR ar_account_id IS NULL THEN\r\n        RAISE WARNING 'Required accounts not found for payment journal entry: Cash=%, AR=%. Available codes: %', \r\n            cash_account_id, ar_account_id, \r\n            (SELECT array_agg(account_code) FROM chart_of_accounts WHERE account_code IN ('1001','1010','1200','1100'));\r\n        RETURN NEW;\r\n    END IF;\r\n    \r\n    -- Get customer name for description\r\n    IF NEW.sales_order_id IS NOT NULL THEN\r\n        SELECT so.customer_name INTO customer_name \r\n        FROM sales_orders so \r\n        WHERE so.id = NEW.sales_order_id;\r\n    ELSIF NEW.invoice_id IS NOT NULL THEN\r\n        SELECT c.name INTO customer_name FROM customers c \r\n        JOIN invoices i ON c.id = i.customer_id \r\n        WHERE i.id = NEW.invoice_id;\r\n    END IF;\r\n    \r\n    -- Create journal entry for payment\r\n    journal_id := create_journal_entry(\r\n        COALESCE(NEW.payment_date::date, NEW.date::date, CURRENT_DATE),\r\n        'Payment received from ' || COALESCE(customer_name, 'Customer'),\r\n        'PAY-' || NEW.id::text\r\n    );\r\n    \r\n    -- Debit Cash (increase asset)\r\n    PERFORM add_journal_entry_line(journal_id, cash_account_id, NEW.amount, 0, 'Cash received');\r\n    \r\n    -- Credit Accounts Receivable (decrease asset)\r\n    PERFORM add_journal_entry_line(journal_id, ar_account_id, 0, NEW.amount, 'Payment applied to receivable');\r\n    \r\n    -- Post the journal entry\r\n    PERFORM post_journal_entry(journal_id);\r\n    \r\n    RETURN NEW;\r\nEXCEPTION\r\n    WHEN OTHERS THEN\r\n        -- Log error and continue without failing the payment\r\n        RAISE WARNING 'Failed to create journal entry for payment %: %', NEW.id, SQLERRM;\r\n        RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "payments",
    "trigger_name": "trg_payments_update_invoice_status",
    "trigger_definition": "CREATE TRIGGER trg_payments_update_invoice_status AFTER INSERT OR DELETE OR UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION trigger_update_invoice_payment_status()",
    "enabled_flag": "O",
    "function_oid": 131986,
    "function_name": "trigger_update_invoice_payment_status",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_update_invoice_payment_status()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    -- Handle different trigger events\r\n    IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN\r\n        -- Update for new/updated payment\r\n        IF NEW.invoice_id IS NOT NULL THEN\r\n            PERFORM update_invoice_payment_status(NEW.invoice_id);\r\n        END IF;\r\n        RETURN NEW;\r\n    ELSIF TG_OP = 'DELETE' THEN\r\n        -- Update for deleted payment\r\n        IF OLD.invoice_id IS NOT NULL THEN\r\n            PERFORM update_invoice_payment_status(OLD.invoice_id);\r\n        END IF;\r\n        RETURN OLD;\r\n    END IF;\r\n    \r\n    RETURN NULL;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "products",
    "trigger_name": "trg_products_set_updated_at",
    "trigger_definition": "CREATE TRIGGER trg_products_set_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION set_updated_at()",
    "enabled_flag": "O",
    "function_oid": 36192,
    "function_name": "set_updated_at",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.set_updated_at()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n  NEW.updated_at = now();\r\n  RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "products",
    "trigger_name": "trg_products_updated_at",
    "trigger_definition": "CREATE TRIGGER trg_products_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()",
    "enabled_flag": "O",
    "function_oid": 36022,
    "function_name": "update_updated_at_column",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_updated_at_column()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    NEW.updated_at = NOW();\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "purchase_order_items",
    "trigger_name": "update_purchase_order_items_updated_at",
    "trigger_definition": "CREATE TRIGGER update_purchase_order_items_updated_at BEFORE UPDATE ON purchase_order_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()",
    "enabled_flag": "O",
    "function_oid": 36022,
    "function_name": "update_updated_at_column",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_updated_at_column()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    NEW.updated_at = NOW();\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "purchase_orders",
    "trigger_name": "trg_purchase_orders_create_journal",
    "trigger_definition": "CREATE TRIGGER trg_purchase_orders_create_journal AFTER INSERT ON purchase_orders FOR EACH ROW EXECUTE FUNCTION trigger_create_purchase_journal_entry()",
    "enabled_flag": "O",
    "function_oid": 132140,
    "function_name": "trigger_create_purchase_journal_entry",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_create_purchase_journal_entry()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n    inventory_account_id UUID;\r\n    ap_account_id UUID;\r\n    journal_id UUID;\r\n    supplier_name TEXT;\r\nBEGIN\r\n    -- Skip if no total amount\r\n    IF NEW.total IS NULL OR NEW.total = 0 THEN\r\n        RETURN NEW;\r\n    END IF;\r\n    \r\n    -- Get account IDs with flexible lookup\r\n    SELECT id INTO inventory_account_id FROM chart_of_accounts WHERE account_code IN ('1300', '1350', '1320') ORDER BY account_code LIMIT 1;\r\n    SELECT id INTO ap_account_id FROM chart_of_accounts WHERE account_code IN ('2010', '2000') ORDER BY account_code LIMIT 1;\r\n    \r\n    -- Skip if accounts not found but log warning\r\n    IF inventory_account_id IS NULL OR ap_account_id IS NULL THEN\r\n        RAISE WARNING 'Required accounts not found for purchase journal entry: Inventory=%, AP=%. Available codes: %', \r\n            inventory_account_id, ap_account_id,\r\n            (SELECT array_agg(account_code) FROM chart_of_accounts WHERE account_code IN ('1300','1350','1320','2010','2000'));\r\n        RETURN NEW;\r\n    END IF;\r\n    \r\n    -- Get supplier name\r\n    IF NEW.supplier_id IS NOT NULL THEN\r\n        SELECT name INTO supplier_name FROM suppliers WHERE id = NEW.supplier_id;\r\n    END IF;\r\n    \r\n    -- Create journal entry for purchase\r\n    journal_id := create_journal_entry(\r\n        COALESCE(NEW.due_date, CURRENT_DATE),\r\n        'Purchase from ' || COALESCE(supplier_name, 'Supplier'),\r\n        'PO-' || NEW.id::text\r\n    );\r\n    \r\n    -- Debit Inventory (increase asset)\r\n    PERFORM add_journal_entry_line(journal_id, inventory_account_id, NEW.total, 0, 'Inventory purchased');\r\n    \r\n    -- Credit Accounts Payable (increase liability)\r\n    PERFORM add_journal_entry_line(journal_id, ap_account_id, 0, NEW.total, 'Amount owed to supplier');\r\n    \r\n    -- Post the journal entry\r\n    PERFORM post_journal_entry(journal_id);\r\n    \r\n    RETURN NEW;\r\nEXCEPTION\r\n    WHEN OTHERS THEN\r\n        -- Log error and continue without failing the purchase order\r\n        RAISE WARNING 'Failed to create journal entry for purchase order %: %', NEW.id, SQLERRM;\r\n        RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "sales_order_items",
    "trigger_name": "calculate_sales_order_item_tax_trigger",
    "trigger_definition": "CREATE TRIGGER calculate_sales_order_item_tax_trigger BEFORE INSERT OR UPDATE ON sales_order_items FOR EACH ROW EXECUTE FUNCTION calculate_sales_order_item_tax()",
    "enabled_flag": "O",
    "function_oid": 124085,
    "function_name": "calculate_sales_order_item_tax",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.calculate_sales_order_item_tax()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n    item_tax_percentage DECIMAL(5,2);\r\nBEGIN\r\n    -- Get tax percentage from parent sales order or use item's own tax percentage\r\n    SELECT COALESCE(so.tax_percentage, NEW.tax_percentage, 18.00)\r\n    INTO item_tax_percentage\r\n    FROM sales_orders so\r\n    WHERE so.id = NEW.order_id;\r\n    \r\n    -- Calculate tax for this item\r\n    NEW.tax_percentage := item_tax_percentage;\r\n    NEW.taxable_amount := NEW.quantity * NEW.final_price;\r\n    NEW.tax_amount := ROUND(NEW.taxable_amount * item_tax_percentage / 100, 2);\r\n    \r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "sales_order_items",
    "trigger_name": "update_sales_order_item_totals_delete",
    "trigger_definition": "CREATE TRIGGER update_sales_order_item_totals_delete AFTER DELETE ON sales_order_items FOR EACH ROW EXECUTE FUNCTION update_sales_order_item_totals()",
    "enabled_flag": "O",
    "function_oid": 124132,
    "function_name": "update_sales_order_item_totals",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_sales_order_item_totals()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n    order_original_price DECIMAL(15,2);\r\n    order_items_subtotal DECIMAL(15,2);\r\n    order_discount_amount DECIMAL(15,2);\r\n    current_freight DECIMAL(15,2);\r\n    current_tax_percentage DECIMAL(5,2);\r\n    current_tax_amount DECIMAL(15,2);\r\n    current_grand_total DECIMAL(15,2);\r\n    current_final_price DECIMAL(15,2);\r\nBEGIN\r\n    -- Get current values to preserve UI calculations\r\n    SELECT \r\n        COALESCE(freight_charges, 0),\r\n        COALESCE(tax_percentage, 18.00),\r\n        COALESCE(tax_amount, 0),\r\n        COALESCE(grand_total, 0),\r\n        COALESCE(final_price, 0)\r\n    INTO \r\n        current_freight,\r\n        current_tax_percentage, \r\n        current_tax_amount,\r\n        current_grand_total,\r\n        current_final_price\r\n    FROM sales_orders \r\n    WHERE id = COALESCE(NEW.order_id, OLD.order_id);\r\n    \r\n    -- Calculate ONLY item-level totals\r\n    SELECT \r\n        COALESCE(SUM(quantity * unit_price), 0),\r\n        COALESCE(SUM(quantity * COALESCE(final_price, unit_price)), 0)\r\n    INTO order_original_price, order_items_subtotal\r\n    FROM sales_order_items \r\n    WHERE order_id = COALESCE(NEW.order_id, OLD.order_id);\r\n    \r\n    order_discount_amount := order_original_price - order_items_subtotal;\r\n    \r\n    -- Update sales_orders - PRESERVE final_price if it was set by UI (includes tax + freight)\r\n    -- Only update final_price if it's currently 0 or matches items subtotal (meaning it wasn't set by UI)\r\n    UPDATE sales_orders SET\r\n        original_price = order_original_price,\r\n        discount_amount = order_discount_amount,\r\n        -- CRITICAL: Only update final_price if it appears to be unset or just item total\r\n        final_price = CASE \r\n            WHEN current_final_price = 0 OR current_final_price = order_items_subtotal THEN \r\n                order_items_subtotal + current_freight + current_tax_amount\r\n            ELSE \r\n                current_final_price  -- PRESERVE UI-calculated final_price\r\n        END,\r\n        -- Always preserve these UI-calculated fields\r\n        freight_charges = current_freight,\r\n        tax_percentage = current_tax_percentage,\r\n        tax_amount = current_tax_amount,\r\n        grand_total = CASE \r\n            WHEN current_grand_total = 0 THEN \r\n                order_items_subtotal + current_freight + current_tax_amount\r\n            ELSE \r\n                current_grand_total  -- PRESERVE UI-calculated grand_total\r\n        END,\r\n        updated_at = NOW()\r\n    WHERE id = COALESCE(NEW.order_id, OLD.order_id);\r\n    \r\n    RETURN COALESCE(NEW, OLD);\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "sales_order_items",
    "trigger_name": "update_sales_order_item_totals_insert",
    "trigger_definition": "CREATE TRIGGER update_sales_order_item_totals_insert AFTER INSERT ON sales_order_items FOR EACH ROW EXECUTE FUNCTION update_sales_order_item_totals()",
    "enabled_flag": "O",
    "function_oid": 124132,
    "function_name": "update_sales_order_item_totals",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_sales_order_item_totals()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n    order_original_price DECIMAL(15,2);\r\n    order_items_subtotal DECIMAL(15,2);\r\n    order_discount_amount DECIMAL(15,2);\r\n    current_freight DECIMAL(15,2);\r\n    current_tax_percentage DECIMAL(5,2);\r\n    current_tax_amount DECIMAL(15,2);\r\n    current_grand_total DECIMAL(15,2);\r\n    current_final_price DECIMAL(15,2);\r\nBEGIN\r\n    -- Get current values to preserve UI calculations\r\n    SELECT \r\n        COALESCE(freight_charges, 0),\r\n        COALESCE(tax_percentage, 18.00),\r\n        COALESCE(tax_amount, 0),\r\n        COALESCE(grand_total, 0),\r\n        COALESCE(final_price, 0)\r\n    INTO \r\n        current_freight,\r\n        current_tax_percentage, \r\n        current_tax_amount,\r\n        current_grand_total,\r\n        current_final_price\r\n    FROM sales_orders \r\n    WHERE id = COALESCE(NEW.order_id, OLD.order_id);\r\n    \r\n    -- Calculate ONLY item-level totals\r\n    SELECT \r\n        COALESCE(SUM(quantity * unit_price), 0),\r\n        COALESCE(SUM(quantity * COALESCE(final_price, unit_price)), 0)\r\n    INTO order_original_price, order_items_subtotal\r\n    FROM sales_order_items \r\n    WHERE order_id = COALESCE(NEW.order_id, OLD.order_id);\r\n    \r\n    order_discount_amount := order_original_price - order_items_subtotal;\r\n    \r\n    -- Update sales_orders - PRESERVE final_price if it was set by UI (includes tax + freight)\r\n    -- Only update final_price if it's currently 0 or matches items subtotal (meaning it wasn't set by UI)\r\n    UPDATE sales_orders SET\r\n        original_price = order_original_price,\r\n        discount_amount = order_discount_amount,\r\n        -- CRITICAL: Only update final_price if it appears to be unset or just item total\r\n        final_price = CASE \r\n            WHEN current_final_price = 0 OR current_final_price = order_items_subtotal THEN \r\n                order_items_subtotal + current_freight + current_tax_amount\r\n            ELSE \r\n                current_final_price  -- PRESERVE UI-calculated final_price\r\n        END,\r\n        -- Always preserve these UI-calculated fields\r\n        freight_charges = current_freight,\r\n        tax_percentage = current_tax_percentage,\r\n        tax_amount = current_tax_amount,\r\n        grand_total = CASE \r\n            WHEN current_grand_total = 0 THEN \r\n                order_items_subtotal + current_freight + current_tax_amount\r\n            ELSE \r\n                current_grand_total  -- PRESERVE UI-calculated grand_total\r\n        END,\r\n        updated_at = NOW()\r\n    WHERE id = COALESCE(NEW.order_id, OLD.order_id);\r\n    \r\n    RETURN COALESCE(NEW, OLD);\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "sales_order_items",
    "trigger_name": "update_sales_order_item_totals_update",
    "trigger_definition": "CREATE TRIGGER update_sales_order_item_totals_update AFTER UPDATE ON sales_order_items FOR EACH ROW EXECUTE FUNCTION update_sales_order_item_totals()",
    "enabled_flag": "O",
    "function_oid": 124132,
    "function_name": "update_sales_order_item_totals",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_sales_order_item_totals()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n    order_original_price DECIMAL(15,2);\r\n    order_items_subtotal DECIMAL(15,2);\r\n    order_discount_amount DECIMAL(15,2);\r\n    current_freight DECIMAL(15,2);\r\n    current_tax_percentage DECIMAL(5,2);\r\n    current_tax_amount DECIMAL(15,2);\r\n    current_grand_total DECIMAL(15,2);\r\n    current_final_price DECIMAL(15,2);\r\nBEGIN\r\n    -- Get current values to preserve UI calculations\r\n    SELECT \r\n        COALESCE(freight_charges, 0),\r\n        COALESCE(tax_percentage, 18.00),\r\n        COALESCE(tax_amount, 0),\r\n        COALESCE(grand_total, 0),\r\n        COALESCE(final_price, 0)\r\n    INTO \r\n        current_freight,\r\n        current_tax_percentage, \r\n        current_tax_amount,\r\n        current_grand_total,\r\n        current_final_price\r\n    FROM sales_orders \r\n    WHERE id = COALESCE(NEW.order_id, OLD.order_id);\r\n    \r\n    -- Calculate ONLY item-level totals\r\n    SELECT \r\n        COALESCE(SUM(quantity * unit_price), 0),\r\n        COALESCE(SUM(quantity * COALESCE(final_price, unit_price)), 0)\r\n    INTO order_original_price, order_items_subtotal\r\n    FROM sales_order_items \r\n    WHERE order_id = COALESCE(NEW.order_id, OLD.order_id);\r\n    \r\n    order_discount_amount := order_original_price - order_items_subtotal;\r\n    \r\n    -- Update sales_orders - PRESERVE final_price if it was set by UI (includes tax + freight)\r\n    -- Only update final_price if it's currently 0 or matches items subtotal (meaning it wasn't set by UI)\r\n    UPDATE sales_orders SET\r\n        original_price = order_original_price,\r\n        discount_amount = order_discount_amount,\r\n        -- CRITICAL: Only update final_price if it appears to be unset or just item total\r\n        final_price = CASE \r\n            WHEN current_final_price = 0 OR current_final_price = order_items_subtotal THEN \r\n                order_items_subtotal + current_freight + current_tax_amount\r\n            ELSE \r\n                current_final_price  -- PRESERVE UI-calculated final_price\r\n        END,\r\n        -- Always preserve these UI-calculated fields\r\n        freight_charges = current_freight,\r\n        tax_percentage = current_tax_percentage,\r\n        tax_amount = current_tax_amount,\r\n        grand_total = CASE \r\n            WHEN current_grand_total = 0 THEN \r\n                order_items_subtotal + current_freight + current_tax_amount\r\n            ELSE \r\n                current_grand_total  -- PRESERVE UI-calculated grand_total\r\n        END,\r\n        updated_at = NOW()\r\n    WHERE id = COALESCE(NEW.order_id, OLD.order_id);\r\n    \r\n    RETURN COALESCE(NEW, OLD);\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "sales_orders",
    "trigger_name": "sales_order_analytics_trigger",
    "trigger_definition": "CREATE TRIGGER sales_order_analytics_trigger AFTER INSERT OR DELETE OR UPDATE ON sales_orders FOR EACH ROW EXECUTE FUNCTION trigger_analytics_update()",
    "enabled_flag": "O",
    "function_oid": 68378,
    "function_name": "trigger_analytics_update",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_analytics_update()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    -- Schedule a refresh of analytics views (in a real implementation, this would be queued)\r\n    PERFORM pg_notify('analytics_refresh', 'scheduled');\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "sales_orders",
    "trigger_name": "trg_sales_orders_create_journal",
    "trigger_definition": "CREATE TRIGGER trg_sales_orders_create_journal AFTER INSERT ON sales_orders FOR EACH ROW EXECUTE FUNCTION trigger_create_sales_journal_entry()",
    "enabled_flag": "O",
    "function_oid": 132138,
    "function_name": "trigger_create_sales_journal_entry",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_create_sales_journal_entry()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n    ar_account_id UUID;\r\n    sales_account_id UUID;\r\n    journal_id UUID;\r\n    customer_name TEXT;\r\n    amount_to_record DECIMAL;\r\nBEGIN\r\n    -- Determine amount to record with better logic\r\n    amount_to_record := COALESCE(NEW.final_price, NEW.total, NEW.total_price, NEW.grand_total, 0);\r\n    \r\n    -- Skip if total is null or zero\r\n    IF amount_to_record IS NULL OR amount_to_record = 0 THEN\r\n        RETURN NEW;\r\n    END IF;\r\n    \r\n    -- Get account IDs with flexible lookup\r\n    SELECT id INTO ar_account_id FROM chart_of_accounts WHERE account_code IN ('1200', '1100') ORDER BY account_code LIMIT 1;\r\n    SELECT id INTO sales_account_id FROM chart_of_accounts WHERE account_code IN ('4010', '4000', '4001') ORDER BY account_code LIMIT 1;\r\n    \r\n    -- Skip if accounts not found but log warning\r\n    IF ar_account_id IS NULL OR sales_account_id IS NULL THEN\r\n        RAISE WARNING 'Required accounts not found for sales journal entry: AR=%, Sales=%. Available codes: %', \r\n            ar_account_id, sales_account_id,\r\n            (SELECT array_agg(account_code) FROM chart_of_accounts WHERE account_code IN ('1200','1100','4010','4000','4001'));\r\n        RETURN NEW;\r\n    END IF;\r\n    \r\n    -- Get customer name\r\n    customer_name := COALESCE(NEW.customer_name, 'Customer');\r\n    \r\n    -- Create journal entry for sale\r\n    journal_id := create_journal_entry(\r\n        CURRENT_DATE,\r\n        'Sale to ' || customer_name,\r\n        CASE \r\n            WHEN TG_TABLE_NAME = 'sales_orders' THEN 'SO-' || NEW.id::text\r\n            WHEN TG_TABLE_NAME = 'invoices' THEN 'INV-' || NEW.id::text\r\n            ELSE 'SALE-' || NEW.id::text\r\n        END\r\n    );\r\n    \r\n    -- Debit Accounts Receivable (increase asset)\r\n    PERFORM add_journal_entry_line(journal_id, ar_account_id, amount_to_record, 0, 'Invoice created');\r\n    \r\n    -- Credit Sales Revenue (increase revenue)\r\n    PERFORM add_journal_entry_line(journal_id, sales_account_id, 0, amount_to_record, 'Sales revenue');\r\n    \r\n    -- Post the journal entry\r\n    PERFORM post_journal_entry(journal_id);\r\n    \r\n    RETURN NEW;\r\nEXCEPTION\r\n    WHEN OTHERS THEN\r\n        -- Log error and continue without failing the sale\r\n        RAISE WARNING 'Failed to create journal entry for sale %: %', NEW.id, SQLERRM;\r\n        RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "sales_orders",
    "trigger_name": "trg_sales_orders_set_updated_at",
    "trigger_definition": "CREATE TRIGGER trg_sales_orders_set_updated_at BEFORE UPDATE ON sales_orders FOR EACH ROW EXECUTE FUNCTION set_updated_at()",
    "enabled_flag": "O",
    "function_oid": 36192,
    "function_name": "set_updated_at",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.set_updated_at()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n  NEW.updated_at = now();\r\n  RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "sales_orders",
    "trigger_name": "trg_sales_orders_updated_at",
    "trigger_definition": "CREATE TRIGGER trg_sales_orders_updated_at BEFORE UPDATE ON sales_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()",
    "enabled_flag": "O",
    "function_oid": 36022,
    "function_name": "update_updated_at_column",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_updated_at_column()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    NEW.updated_at = NOW();\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "stock_adjustments",
    "trigger_name": "apply_stock_adjustment_trigger",
    "trigger_definition": "CREATE TRIGGER apply_stock_adjustment_trigger AFTER INSERT ON stock_adjustments FOR EACH ROW EXECUTE FUNCTION apply_stock_adjustment()",
    "enabled_flag": "O",
    "function_oid": 94165,
    "function_name": "apply_stock_adjustment",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.apply_stock_adjustment()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n  UPDATE inventory_items\r\n  SET quantity = NEW.quantity_after,\r\n      updated_at = NOW()\r\n  WHERE id = NEW.inventory_item_id;\r\n  RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "stock_adjustments",
    "trigger_name": "stock_adjustments_updated_at_trigger",
    "trigger_definition": "CREATE TRIGGER stock_adjustments_updated_at_trigger BEFORE UPDATE ON stock_adjustments FOR EACH ROW EXECUTE FUNCTION update_stock_adjustments_updated_at()",
    "enabled_flag": "O",
    "function_oid": 94163,
    "function_name": "update_stock_adjustments_updated_at",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_stock_adjustments_updated_at()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n  NEW.updated_at = NOW();\r\n  RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "suppliers",
    "trigger_name": "trg_suppliers_set_updated_at",
    "trigger_definition": "CREATE TRIGGER trg_suppliers_set_updated_at BEFORE UPDATE ON suppliers FOR EACH ROW EXECUTE FUNCTION set_updated_at()",
    "enabled_flag": "O",
    "function_oid": 36192,
    "function_name": "set_updated_at",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.set_updated_at()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n  NEW.updated_at = now();\r\n  RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "suppliers",
    "trigger_name": "trg_suppliers_updated_at",
    "trigger_definition": "CREATE TRIGGER trg_suppliers_updated_at BEFORE UPDATE ON suppliers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()",
    "enabled_flag": "O",
    "function_oid": 36022,
    "function_name": "update_updated_at_column",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_updated_at_column()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    NEW.updated_at = NOW();\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "support_tickets",
    "trigger_name": "update_support_tickets_updated_at",
    "trigger_definition": "CREATE TRIGGER update_support_tickets_updated_at BEFORE UPDATE ON support_tickets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()",
    "enabled_flag": "O",
    "function_oid": 36022,
    "function_name": "update_updated_at_column",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_updated_at_column()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    NEW.updated_at = NOW();\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "user_notification_settings",
    "trigger_name": "update_user_notification_settings_updated_at",
    "trigger_definition": "CREATE TRIGGER update_user_notification_settings_updated_at BEFORE UPDATE ON user_notification_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()",
    "enabled_flag": "O",
    "function_oid": 36022,
    "function_name": "update_updated_at_column",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_updated_at_column()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    NEW.updated_at = NOW();\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "vendor_payment_history",
    "trigger_name": "trg_vendor_payments_audit",
    "trigger_definition": "CREATE TRIGGER trg_vendor_payments_audit BEFORE INSERT ON vendor_payment_history FOR EACH ROW EXECUTE FUNCTION trigger_audit_financial_transaction()",
    "enabled_flag": "O",
    "function_oid": 132003,
    "function_name": "trigger_audit_financial_transaction",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_audit_financial_transaction()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    -- This can be extended to log to an audit table\r\n    -- For now, just ensure created_at is set\r\n    IF TG_OP = 'INSERT' THEN\r\n        IF NEW.created_at IS NULL THEN\r\n            NEW.created_at = CURRENT_TIMESTAMP;\r\n        END IF;\r\n        RETURN NEW;\r\n    END IF;\r\n    \r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "vendor_payment_history",
    "trigger_name": "trg_vendor_payments_create_journal",
    "trigger_definition": "CREATE TRIGGER trg_vendor_payments_create_journal AFTER INSERT ON vendor_payment_history FOR EACH ROW EXECUTE FUNCTION trigger_create_vendor_payment_journal_entry()",
    "enabled_flag": "O",
    "function_oid": 132139,
    "function_name": "trigger_create_vendor_payment_journal_entry",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_create_vendor_payment_journal_entry()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nDECLARE\r\n    cash_account_id UUID;\r\n    ap_account_id UUID;\r\n    journal_id UUID;\r\n    supplier_name TEXT;\r\n    payment_amount DECIMAL;\r\nBEGIN\r\n    -- Determine payment amount (handle different column names)\r\n    payment_amount := COALESCE(NEW.amount_paid, NEW.amount, 0);\r\n    \r\n    -- Skip if amount is null or zero\r\n    IF payment_amount IS NULL OR payment_amount = 0 THEN\r\n        RETURN NEW;\r\n    END IF;\r\n    \r\n    -- Skip if payment is not completed (if status field exists)\r\n    IF NEW.status IS NOT NULL AND NEW.status != 'completed' THEN\r\n        RETURN NEW;\r\n    END IF;\r\n    \r\n    -- Get account IDs with flexible lookup\r\n    SELECT id INTO cash_account_id FROM chart_of_accounts WHERE account_code IN ('1001', '1010') ORDER BY account_code LIMIT 1;\r\n    SELECT id INTO ap_account_id FROM chart_of_accounts WHERE account_code IN ('2010', '2000') ORDER BY account_code LIMIT 1;\r\n    \r\n    -- Skip if accounts not found but log warning\r\n    IF cash_account_id IS NULL OR ap_account_id IS NULL THEN\r\n        RAISE WARNING 'Required accounts not found for vendor payment journal entry: Cash=%, AP=%. Available codes: %', \r\n            cash_account_id, ap_account_id,\r\n            (SELECT array_agg(account_code) FROM chart_of_accounts WHERE account_code IN ('1001','1010','2010','2000'));\r\n        RETURN NEW;\r\n    END IF;\r\n    \r\n    -- Get supplier name\r\n    IF NEW.supplier_id IS NOT NULL THEN\r\n        SELECT name INTO supplier_name FROM suppliers WHERE id = NEW.supplier_id;\r\n    END IF;\r\n    \r\n    -- Create journal entry for vendor payment\r\n    journal_id := create_journal_entry(\r\n        COALESCE(NEW.payment_date, CURRENT_DATE),\r\n        'Payment to ' || COALESCE(supplier_name, 'Supplier'),\r\n        'VP-' || NEW.id::text\r\n    );\r\n    \r\n    -- Debit Accounts Payable (decrease liability)\r\n    PERFORM add_journal_entry_line(journal_id, ap_account_id, payment_amount, 0, 'Payment to supplier');\r\n    \r\n    -- Credit Cash (decrease asset)\r\n    PERFORM add_journal_entry_line(journal_id, cash_account_id, 0, payment_amount, 'Cash paid');\r\n    \r\n    -- Post the journal entry\r\n    PERFORM post_journal_entry(journal_id);\r\n    \r\n    RETURN NEW;\r\nEXCEPTION\r\n    WHEN OTHERS THEN\r\n        -- Log error and continue without failing the payment\r\n        RAISE WARNING 'Failed to create journal entry for vendor payment %: %', NEW.id, SQLERRM;\r\n        RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "vendor_payment_history",
    "trigger_name": "trg_vendor_payments_update_po_status",
    "trigger_definition": "CREATE TRIGGER trg_vendor_payments_update_po_status AFTER INSERT OR DELETE OR UPDATE ON vendor_payment_history FOR EACH ROW EXECUTE FUNCTION trigger_update_po_payment_status()",
    "enabled_flag": "O",
    "function_oid": 131988,
    "function_name": "trigger_update_po_payment_status",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.trigger_update_po_payment_status()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    -- Handle different trigger events\r\n    IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN\r\n        -- Update for new/updated vendor payment\r\n        IF NEW.purchase_order_id IS NOT NULL THEN\r\n            PERFORM update_purchase_order_payment_status(NEW.purchase_order_id);\r\n        END IF;\r\n        RETURN NEW;\r\n    ELSIF TG_OP = 'DELETE' THEN\r\n        -- Update for deleted vendor payment\r\n        IF OLD.purchase_order_id IS NOT NULL THEN\r\n            PERFORM update_purchase_order_payment_status(OLD.purchase_order_id);\r\n        END IF;\r\n        RETURN OLD;\r\n    END IF;\r\n    \r\n    RETURN NULL;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "vendor_payment_history",
    "trigger_name": "trigger_update_po_payment_status",
    "trigger_definition": "CREATE TRIGGER trigger_update_po_payment_status AFTER INSERT OR DELETE OR UPDATE ON vendor_payment_history FOR EACH ROW EXECUTE FUNCTION update_purchase_order_payment_status()",
    "enabled_flag": "O",
    "function_oid": 76650,
    "function_name": "update_purchase_order_payment_status",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_purchase_order_payment_status()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    UPDATE purchase_orders \r\n    SET payment_status = CASE \r\n        WHEN paid_amount = 0 THEN 'unpaid'\r\n        WHEN paid_amount >= total THEN 'paid'\r\n        WHEN paid_amount > 0 AND paid_amount < total THEN 'partially_paid'\r\n        ELSE payment_status\r\n    END\r\n    WHERE id = COALESCE(NEW.purchase_order_id, OLD.purchase_order_id);\r\n\r\n    RETURN COALESCE(NEW, OLD);\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "vendor_payment_history",
    "trigger_name": "trigger_update_vendor_bill_status",
    "trigger_definition": "CREATE TRIGGER trigger_update_vendor_bill_status AFTER INSERT OR DELETE OR UPDATE ON vendor_payment_history FOR EACH ROW EXECUTE FUNCTION update_vendor_bill_status()",
    "enabled_flag": "O",
    "function_oid": 76648,
    "function_name": "update_vendor_bill_status",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_vendor_bill_status()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    UPDATE vendor_bills \r\n    SET status = CASE \r\n        WHEN paid_amount = 0 THEN 'pending'\r\n        WHEN paid_amount >= total_amount THEN 'paid'\r\n        WHEN paid_amount > 0 AND paid_amount < total_amount THEN 'partial'\r\n        ELSE status\r\n    END,\r\n    updated_at = now()\r\n    WHERE id = COALESCE(NEW.vendor_bill_id, OLD.vendor_bill_id);\r\n\r\n    RETURN COALESCE(NEW, OLD);\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "work_orders",
    "trigger_name": "trg_work_orders_set_updated_at",
    "trigger_definition": "CREATE TRIGGER trg_work_orders_set_updated_at BEFORE UPDATE ON work_orders FOR EACH ROW EXECUTE FUNCTION set_updated_at()",
    "enabled_flag": "O",
    "function_oid": 36192,
    "function_name": "set_updated_at",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.set_updated_at()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n  NEW.updated_at = now();\r\n  RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "public",
    "table_name": "work_orders",
    "trigger_name": "trg_work_orders_updated_at",
    "trigger_definition": "CREATE TRIGGER trg_work_orders_updated_at BEFORE UPDATE ON work_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()",
    "enabled_flag": "O",
    "function_oid": 36022,
    "function_name": "update_updated_at_column",
    "function_owner": "postgres",
    "function_definition": "CREATE OR REPLACE FUNCTION public.update_updated_at_column()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\r\nBEGIN\r\n    NEW.updated_at = NOW();\r\n    RETURN NEW;\r\nEND;\r\n$function$\n"
  },
  {
    "trigger_schema": "realtime",
    "table_name": "subscription",
    "trigger_name": "tr_check_filters",
    "trigger_definition": "CREATE TRIGGER tr_check_filters BEFORE INSERT OR UPDATE ON realtime.subscription FOR EACH ROW EXECUTE FUNCTION realtime.subscription_check_filters()",
    "enabled_flag": "O",
    "function_oid": 17119,
    "function_name": "subscription_check_filters",
    "function_owner": "supabase_admin",
    "function_definition": "CREATE OR REPLACE FUNCTION realtime.subscription_check_filters()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\n    /*\n    Validates that the user defined filters for a subscription:\n    - refer to valid columns that the claimed role may access\n    - values are coercable to the correct column type\n    */\n    declare\n        col_names text[] = coalesce(\n                array_agg(c.column_name order by c.ordinal_position),\n                '{}'::text[]\n            )\n            from\n                information_schema.columns c\n            where\n                format('%I.%I', c.table_schema, c.table_name)::regclass = new.entity\n                and pg_catalog.has_column_privilege(\n                    (new.claims ->> 'role'),\n                    format('%I.%I', c.table_schema, c.table_name)::regclass,\n                    c.column_name,\n                    'SELECT'\n                );\n        filter realtime.user_defined_filter;\n        col_type regtype;\n\n        in_val jsonb;\n    begin\n        for filter in select * from unnest(new.filters) loop\n            -- Filtered column is valid\n            if not filter.column_name = any(col_names) then\n                raise exception 'invalid column for filter %', filter.column_name;\n            end if;\n\n            -- Type is sanitized and safe for string interpolation\n            col_type = (\n                select atttypid::regtype\n                from pg_catalog.pg_attribute\n                where attrelid = new.entity\n                      and attname = filter.column_name\n            );\n            if col_type is null then\n                raise exception 'failed to lookup type for column %', filter.column_name;\n            end if;\n\n            -- Set maximum number of entries for in filter\n            if filter.op = 'in'::realtime.equality_op then\n                in_val = realtime.cast(filter.value, (col_type::text || '[]')::regtype);\n                if coalesce(jsonb_array_length(in_val), 0) > 100 then\n                    raise exception 'too many values for `in` filter. Maximum 100';\n                end if;\n            else\n                -- raises an exception if value is not coercable to type\n                perform realtime.cast(filter.value, col_type);\n            end if;\n\n        end loop;\n\n        -- Apply consistent order to filters so the unique constraint on\n        -- (subscription_id, entity, filters) can't be tricked by a different filter order\n        new.filters = coalesce(\n            array_agg(f order by f.column_name, f.op, f.value),\n            '{}'\n        ) from unnest(new.filters) f;\n\n        return new;\n    end;\n    $function$\n"
  },
  {
    "trigger_schema": "storage",
    "table_name": "buckets",
    "trigger_name": "enforce_bucket_name_length_trigger",
    "trigger_definition": "CREATE TRIGGER enforce_bucket_name_length_trigger BEFORE INSERT OR UPDATE OF name ON storage.buckets FOR EACH ROW EXECUTE FUNCTION storage.enforce_bucket_name_length()",
    "enabled_flag": "O",
    "function_oid": 117653,
    "function_name": "enforce_bucket_name_length",
    "function_owner": "supabase_storage_admin",
    "function_definition": "CREATE OR REPLACE FUNCTION storage.enforce_bucket_name_length()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\nbegin\n    if length(new.name) > 100 then\n        raise exception 'bucket name \"%\" is too long (% characters). Max is 100.', new.name, length(new.name);\n    end if;\n    return new;\nend;\n$function$\n"
  },
  {
    "trigger_schema": "storage",
    "table_name": "objects",
    "trigger_name": "objects_delete_delete_prefix",
    "trigger_definition": "CREATE TRIGGER objects_delete_delete_prefix AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger()",
    "enabled_flag": "O",
    "function_oid": 117638,
    "function_name": "delete_prefix_hierarchy_trigger",
    "function_owner": "supabase_storage_admin",
    "function_definition": "CREATE OR REPLACE FUNCTION storage.delete_prefix_hierarchy_trigger()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\nDECLARE\n    prefix text;\nBEGIN\n    prefix := \"storage\".\"get_prefix\"(OLD.\"name\");\n\n    IF coalesce(prefix, '') != '' THEN\n        PERFORM \"storage\".\"delete_prefix\"(OLD.\"bucket_id\", prefix);\n    END IF;\n\n    RETURN OLD;\nEND;\n$function$\n"
  },
  {
    "trigger_schema": "storage",
    "table_name": "objects",
    "trigger_name": "objects_insert_create_prefix",
    "trigger_definition": "CREATE TRIGGER objects_insert_create_prefix BEFORE INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.objects_insert_prefix_trigger()",
    "enabled_flag": "O",
    "function_oid": 117637,
    "function_name": "objects_insert_prefix_trigger",
    "function_owner": "supabase_storage_admin",
    "function_definition": "CREATE OR REPLACE FUNCTION storage.objects_insert_prefix_trigger()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\nBEGIN\n    PERFORM \"storage\".\"add_prefixes\"(NEW.\"bucket_id\", NEW.\"name\");\n    NEW.level := \"storage\".\"get_level\"(NEW.\"name\");\n\n    RETURN NEW;\nEND;\n$function$\n"
  },
  {
    "trigger_schema": "storage",
    "table_name": "objects",
    "trigger_name": "objects_update_create_prefix",
    "trigger_definition": "CREATE TRIGGER objects_update_create_prefix BEFORE UPDATE ON storage.objects FOR EACH ROW WHEN (new.name <> old.name OR new.bucket_id <> old.bucket_id) EXECUTE FUNCTION storage.objects_update_prefix_trigger()",
    "enabled_flag": "O",
    "function_oid": 117652,
    "function_name": "objects_update_prefix_trigger",
    "function_owner": "supabase_storage_admin",
    "function_definition": "CREATE OR REPLACE FUNCTION storage.objects_update_prefix_trigger()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\nDECLARE\n    old_prefixes TEXT[];\nBEGIN\n    -- Ensure this is an update operation and the name has changed\n    IF TG_OP = 'UPDATE' AND (NEW.\"name\" <> OLD.\"name\" OR NEW.\"bucket_id\" <> OLD.\"bucket_id\") THEN\n        -- Retrieve old prefixes\n        old_prefixes := \"storage\".\"get_prefixes\"(OLD.\"name\");\n\n        -- Remove old prefixes that are only used by this object\n        WITH all_prefixes as (\n            SELECT unnest(old_prefixes) as prefix\n        ),\n        can_delete_prefixes as (\n             SELECT prefix\n             FROM all_prefixes\n             WHERE NOT EXISTS (\n                 SELECT 1 FROM \"storage\".\"objects\"\n                 WHERE \"bucket_id\" = OLD.\"bucket_id\"\n                   AND \"name\" <> OLD.\"name\"\n                   AND \"name\" LIKE (prefix || '%')\n             )\n         )\n        DELETE FROM \"storage\".\"prefixes\" WHERE name IN (SELECT prefix FROM can_delete_prefixes);\n\n        -- Add new prefixes\n        PERFORM \"storage\".\"add_prefixes\"(NEW.\"bucket_id\", NEW.\"name\");\n    END IF;\n    -- Set the new level\n    NEW.\"level\" := \"storage\".\"get_level\"(NEW.\"name\");\n\n    RETURN NEW;\nEND;\n$function$\n"
  },
  {
    "trigger_schema": "storage",
    "table_name": "objects",
    "trigger_name": "update_objects_updated_at",
    "trigger_definition": "CREATE TRIGGER update_objects_updated_at BEFORE UPDATE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.update_updated_at_column()",
    "enabled_flag": "O",
    "function_oid": 17023,
    "function_name": "update_updated_at_column",
    "function_owner": "supabase_storage_admin",
    "function_definition": "CREATE OR REPLACE FUNCTION storage.update_updated_at_column()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\nBEGIN\n    NEW.updated_at = now();\n    RETURN NEW; \nEND;\n$function$\n"
  },
  {
    "trigger_schema": "storage",
    "table_name": "prefixes",
    "trigger_name": "prefixes_create_hierarchy",
    "trigger_definition": "CREATE TRIGGER prefixes_create_hierarchy BEFORE INSERT ON storage.prefixes FOR EACH ROW WHEN (pg_trigger_depth() < 1) EXECUTE FUNCTION storage.prefixes_insert_trigger()",
    "enabled_flag": "O",
    "function_oid": 117636,
    "function_name": "prefixes_insert_trigger",
    "function_owner": "supabase_storage_admin",
    "function_definition": "CREATE OR REPLACE FUNCTION storage.prefixes_insert_trigger()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\nBEGIN\n    PERFORM \"storage\".\"add_prefixes\"(NEW.\"bucket_id\", NEW.\"name\");\n    RETURN NEW;\nEND;\n$function$\n"
  },
  {
    "trigger_schema": "storage",
    "table_name": "prefixes",
    "trigger_name": "prefixes_delete_hierarchy",
    "trigger_definition": "CREATE TRIGGER prefixes_delete_hierarchy AFTER DELETE ON storage.prefixes FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger()",
    "enabled_flag": "O",
    "function_oid": 117638,
    "function_name": "delete_prefix_hierarchy_trigger",
    "function_owner": "supabase_storage_admin",
    "function_definition": "CREATE OR REPLACE FUNCTION storage.delete_prefix_hierarchy_trigger()\n RETURNS trigger\n LANGUAGE plpgsql\nAS $function$\nDECLARE\n    prefix text;\nBEGIN\n    prefix := \"storage\".\"get_prefix\"(OLD.\"name\");\n\n    IF coalesce(prefix, '') != '' THEN\n        PERFORM \"storage\".\"delete_prefix\"(OLD.\"bucket_id\", prefix);\n    END IF;\n\n    RETURN OLD;\nEND;\n$function$\n"
  }
]